/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.validacion;

// Generated 18-jul-2011 17:35:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResultadoId generated by hbm2java
 */
@Embeddable
public class ResultadoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2881892815128316616L;
	private int idproceso;
	private int idvalidacion;

	public ResultadoId() {
	}

	public ResultadoId(int idproceso, int idvalidacion) {
		this.idproceso = idproceso;
		this.idvalidacion = idvalidacion;
	}

	@Column(name = "idproceso", nullable = false)
	public int getIdproceso() {
		return this.idproceso;
	}

	public void setIdproceso(int idproceso) {
		this.idproceso = idproceso;
	}

	@Column(name = "idvalidacion", nullable = false)
	public int getIdvalidacion() {
		return this.idvalidacion;
	}

	public void setIdvalidacion(int idvalidacion) {
		this.idvalidacion = idvalidacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResultadoId))
			return false;
		ResultadoId castOther = (ResultadoId) other;

		return (this.getIdproceso() == castOther.getIdproceso())
				&& (this.getIdvalidacion() == castOther.getIdvalidacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproceso();
		result = 37 * result + this.getIdvalidacion();
		return result;
	}

}
