/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.validacion;

// Generated 18-jul-2011 17:35:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Validacion generated by hbm2java
 */
@Entity
@Table(name = "validacion", schema="validacion")
public class Validacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8363909077454684244L;
	private int iden;
	private int tipovalidacion;
	private Integer tipoerror;
	private boolean activado;
	private String nemo;
	private String descripcion;
	private String sentencia;
	private String resultadoesperado;
	private String columnas;
	private String mensaje;
	private Set<Resultado> resultados = new HashSet<Resultado>(0);

	public Validacion() {
	}

	public Validacion(int iden, int tipovalidacion, boolean activado,
			String descripcion, String sentencia, String resultadoesperado) {
		this.iden = iden;
		this.tipovalidacion = tipovalidacion;
		this.activado = activado;
		this.descripcion = descripcion;
		this.sentencia = sentencia;
		this.resultadoesperado = resultadoesperado;
	}

	public Validacion(int iden, int tipovalidacion, Integer tipoerror,
			boolean activado, String nemo, String descripcion,
			String sentencia, String resultadoesperado, String columnas,
			String mensaje, Set<Resultado> resultados) {
		this.iden = iden;
		this.tipovalidacion = tipovalidacion;
		this.tipoerror = tipoerror;
		this.activado = activado;
		this.nemo = nemo;
		this.descripcion = descripcion;
		this.sentencia = sentencia;
		this.resultadoesperado = resultadoesperado;
		this.columnas = columnas;
		this.mensaje = mensaje;
		this.resultados = resultados;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@Column(name = "tipovalidacion", nullable = false)
	public int getTipovalidacion() {
		return this.tipovalidacion;
	}

	public void setTipovalidacion(int tipovalidacion) {
		this.tipovalidacion = tipovalidacion;
	}

	@Column(name = "tipoerror")
	public Integer getTipoerror() {
		return this.tipoerror;
	}

	public void setTipoerror(Integer tipoerror) {
		this.tipoerror = tipoerror;
	}

	@Column(name = "activado", nullable = false)
	public boolean isActivado() {
		return this.activado;
	}

	public void setActivado(boolean activado) {
		this.activado = activado;
	}

	@Column(name = "nemo", length = 10)
	public String getNemo() {
		return this.nemo;
	}

	public void setNemo(String nemo) {
		this.nemo = nemo;
	}

	@Column(name = "descripcion", nullable = false, length = 3000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "sentencia", nullable = false, length = 3000)
	public String getSentencia() {
		return this.sentencia;
	}

	public void setSentencia(String sentencia) {
		this.sentencia = sentencia;
	}

	@Column(name = "resultadoesperado", nullable = false, length = 1000)
	public String getResultadoesperado() {
		return this.resultadoesperado;
	}

	public void setResultadoesperado(String resultadoesperado) {
		this.resultadoesperado = resultadoesperado;
	}

	@Column(name = "columnas", length = 3000)
	public String getColumnas() {
		return this.columnas;
	}

	public void setColumnas(String columnas) {
		this.columnas = columnas;
	}

	@Column(name = "mensaje", length = 3000)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "validacion")
	public Set<Resultado> getResultados() {
		return this.resultados;
	}

	public void setResultados(Set<Resultado> resultados) {
		this.resultados = resultados;
	}

}
