package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Relacion generated by hbm2java
 */
@Entity
@Table(name = "relacion")
public class Relacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 111445315704878760L;
	private int iden;
	private Tramite tramiteByIdtramiteborrador;
	private Tramite tramiteByIdtramitecreador;
	private int iddefrelacion;
	private Set<Operacionrelacion> operacionrelacions = new HashSet<Operacionrelacion>(
			0);
	private Set<Propiedadrelacion> propiedadrelacions = new HashSet<Propiedadrelacion>(
			0);
	private Set<Vectorrelacion> vectorrelacions = new HashSet<Vectorrelacion>(0);

	public Relacion() {
	}

	public Relacion(int iden, Tramite tramiteByIdtramitecreador,
			int iddefrelacion) {
		this.iden = iden;
		this.tramiteByIdtramitecreador = tramiteByIdtramitecreador;
		this.iddefrelacion = iddefrelacion;
	}

	public Relacion(int iden, Tramite tramiteByIdtramiteborrador,
			Tramite tramiteByIdtramitecreador, int iddefrelacion,
			Set<Operacionrelacion> operacionrelacions,
			Set<Propiedadrelacion> propiedadrelacions,
			Set<Vectorrelacion> vectorrelacions) {
		this.iden = iden;
		this.tramiteByIdtramiteborrador = tramiteByIdtramiteborrador;
		this.tramiteByIdtramitecreador = tramiteByIdtramitecreador;
		this.iddefrelacion = iddefrelacion;
		this.operacionrelacions = operacionrelacions;
		this.propiedadrelacions = propiedadrelacions;
		this.vectorrelacions = vectorrelacions;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtramiteborrador")
	public Tramite getTramiteByIdtramiteborrador() {
		return this.tramiteByIdtramiteborrador;
	}

	public void setTramiteByIdtramiteborrador(Tramite tramiteByIdtramiteborrador) {
		this.tramiteByIdtramiteborrador = tramiteByIdtramiteborrador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtramitecreador", nullable = false)
	public Tramite getTramiteByIdtramitecreador() {
		return this.tramiteByIdtramitecreador;
	}

	public void setTramiteByIdtramitecreador(Tramite tramiteByIdtramitecreador) {
		this.tramiteByIdtramitecreador = tramiteByIdtramitecreador;
	}

	@Column(name = "iddefrelacion", nullable = false)
	public int getIddefrelacion() {
		return this.iddefrelacion;
	}

	public void setIddefrelacion(int iddefrelacion) {
		this.iddefrelacion = iddefrelacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relacion")
	public Set<Operacionrelacion> getOperacionrelacions() {
		return this.operacionrelacions;
	}

	public void setOperacionrelacions(Set<Operacionrelacion> operacionrelacions) {
		this.operacionrelacions = operacionrelacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relacion")
	public Set<Propiedadrelacion> getPropiedadrelacions() {
		return this.propiedadrelacions;
	}

	public void setPropiedadrelacions(Set<Propiedadrelacion> propiedadrelacions) {
		this.propiedadrelacions = propiedadrelacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relacion")
	public Set<Vectorrelacion> getVectorrelacions() {
		return this.vectorrelacions;
	}

	public void setVectorrelacions(Set<Vectorrelacion> vectorrelacions) {
		this.vectorrelacions = vectorrelacions;
	}

}
