
package es.mitc.redes.urbanismoenred.servicios.refundido;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RefundidoWebServiceService", targetNamespace = "http://refundido.servicios.urbanismoenred.redes.mitc.es/", wsdlLocation = "http://127.0.0.1:9080/Urbanismoenred-serviciosV2/RefundidoWebService?wsdl")
public class RefundidoWebServiceService
    extends Service
{

    private final static URL REFUNDIDOWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.mitc.redes.urbanismoenred.servicios.refundido.RefundidoWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.mitc.redes.urbanismoenred.servicios.refundido.RefundidoWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9080/Urbanismoenred-serviciosV2/RefundidoWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9080/Urbanismoenred-serviciosV2/RefundidoWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REFUNDIDOWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public RefundidoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RefundidoWebServiceService() {
        super(REFUNDIDOWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://refundido.servicios.urbanismoenred.redes.mitc.es/", "RefundidoWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns RefundidoWebServiceInterface
     */
    @WebEndpoint(name = "RefundidoWebServicePort")
    public RefundidoWebServiceInterface getRefundidoWebServicePort() {
        return super.getPort(new QName("http://refundido.servicios.urbanismoenred.redes.mitc.es/", "RefundidoWebServicePort"), RefundidoWebServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundidoWebServiceInterface
     */
    @WebEndpoint(name = "RefundidoWebServicePort")
    public RefundidoWebServiceInterface getRefundidoWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://refundido.servicios.urbanismoenred.redes.mitc.es/", "RefundidoWebServicePort"), RefundidoWebServiceInterface.class, features);
    }

}
