/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.seguridad;
// Generated 13-oct-2009 13:54:46 by Hibernate Tools 3.2.1.GA

import es.mitc.redes.urbanismoenred.data.rpm.diccionario.Ambito;



/**
 * Usuariorol generated by hbm2java
 */
public class Usuariorol  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6404824329957786744L;
	private int iden;
     private Usuario usuario;
     private Rol rol;
     private Ambito ambito;
     

    public Usuariorol() {
    }

    public Usuariorol(int iden, Usuario usuario, Rol rol) {
       this.iden = iden;
       this.usuario = usuario;
       this.rol = rol;
       
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public Ambito getAmbito(){
        return this.ambito;
    }

    public void setAmbito(Ambito ambito){
        this.ambito = ambito;
    }


}


