//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Regulación especófica de la determinación en carpetas (definidas por la recursividad HIJAS).
 * 
 * 
 * <p>Java class for RegulacionEspecifica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulacionEspecifica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TEXTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HIJAS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="REGULACION-ESPECIFICA" type="{}RegulacionEspecifica" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="orden" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulacionEspecifica", propOrder = {
    "texto",
    "hijas"
})
public class RegulacionEspecifica {

    @XmlElement(name = "TEXTO", required = true)
    protected String texto;
    @XmlElement(name = "HIJAS")
    protected RegulacionEspecifica.HIJAS hijas;
    @XmlAttribute(name = "orden", required = true)
    protected BigInteger orden;
    @XmlAttribute(name = "nombre", required = true)
    protected String nombre;

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the hijas property.
     * 
     * @return
     *     possible object is
     *     {@link RegulacionEspecifica.HIJAS }
     *     
     */
    public RegulacionEspecifica.HIJAS getHIJAS() {
        return hijas;
    }

    /**
     * Sets the value of the hijas property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulacionEspecifica.HIJAS }
     *     
     */
    public void setHIJAS(RegulacionEspecifica.HIJAS value) {
        this.hijas = value;
    }

    /**
     * Gets the value of the orden property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrden() {
        return orden;
    }

    /**
     * Sets the value of the orden property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrden(BigInteger value) {
        this.orden = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="REGULACION-ESPECIFICA" type="{}RegulacionEspecifica" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regulacionespecifica"
    })
    public static class HIJAS {

        @XmlElement(name = "REGULACION-ESPECIFICA", required = true)
        protected List<RegulacionEspecifica> regulacionespecifica;

        /**
         * Gets the value of the regulacionespecifica property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the regulacionespecifica property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getREGULACIONESPECIFICA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RegulacionEspecifica }
         * 
         * 
         */
        public List<RegulacionEspecifica> getREGULACIONESPECIFICA() {
            if (regulacionespecifica == null) {
                regulacionespecifica = new ArrayList<RegulacionEspecifica>();
            }
            return this.regulacionespecifica;
        }

    }

}
