package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Operacionentidad generated by hbm2java
 */
@Entity
@Table(name = "operacionentidad")
public class Operacionentidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5873730282044223072L;
	private int iden;
	private Entidad entidadByIdentidadoperadora;
	private Entidad entidadByIdentidad;
	private Operacion operacion;
	private int idtipooperacionent;

	public Operacionentidad() {
	}

	public Operacionentidad(int iden, Entidad entidadByIdentidadoperadora,
			Entidad entidadByIdentidad, Operacion operacion,
			int idtipooperacionent) {
		this.iden = iden;
		this.entidadByIdentidadoperadora = entidadByIdentidadoperadora;
		this.entidadByIdentidad = entidadByIdentidad;
		this.operacion = operacion;
		this.idtipooperacionent = idtipooperacionent;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identidadoperadora", nullable = false)
	public Entidad getEntidadByIdentidadoperadora() {
		return this.entidadByIdentidadoperadora;
	}

	public void setEntidadByIdentidadoperadora(
			Entidad entidadByIdentidadoperadora) {
		this.entidadByIdentidadoperadora = entidadByIdentidadoperadora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identidad", nullable = false)
	public Entidad getEntidadByIdentidad() {
		return this.entidadByIdentidad;
	}

	public void setEntidadByIdentidad(Entidad entidadByIdentidad) {
		this.entidadByIdentidad = entidadByIdentidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperacion", nullable = false)
	public Operacion getOperacion() {
		return this.operacion;
	}

	public void setOperacion(Operacion operacion) {
		this.operacion = operacion;
	}

	@Column(name = "idtipooperacionent", nullable = false)
	public int getIdtipooperacionent() {
		return this.idtipooperacionent;
	}

	public void setIdtipooperacionent(int idtipooperacionent) {
		this.idtipooperacionent = idtipooperacionent;
	}

}
