/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Boletintramite generated by hbm2java
 */
public class Boletintramite  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2601940925186335006L;
	private int iden;
     private Tramite tramite;
     private int idboletin;
     private Date fecha;
     private String numero;

    public Boletintramite() {
    }

	
    public Boletintramite(int iden, Tramite tramite, int idboletin) {
        this.iden = iden;
        this.tramite = tramite;
        this.idboletin = idboletin;
    }
    public Boletintramite(int iden, Tramite tramite, int idboletin, Date fecha, String numero) {
       this.iden = iden;
       this.tramite = tramite;
       this.idboletin = idboletin;
       this.fecha = fecha;
       this.numero = numero;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Tramite getTramite() {
        return this.tramite;
    }
    
    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }
    public int getIdboletin() {
        return this.idboletin;
    }
    
    public void setIdboletin(int idboletin) {
        this.idboletin = idboletin;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


