/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;

import java.util.Set;


/**
 * Determinacion generated by hbm2java
 */
public class Determinacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7433984653817639530L;
	private int iden;
     private Tramite tramite;
     private Determinacion determinacionByIddeterminacionoriginal;
     private Determinacion determinacionByIddeterminacionbase;
     private Determinacion determinacionByIdpadre;
     private int idcaracter;
     private String apartado;
     private String nombre;
     private String texto;
     private String etiqueta;
     private String codigo;
     private boolean bsuspendida;
     private int orden;
     private Set<Documentodeterminacion> documentodeterminacions = new HashSet<Documentodeterminacion>(0);
     private Set<Determinacion> determinacionsForIdpadre = new HashSet<Determinacion>(0);
     private Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminaciongrupo = new HashSet<Determinaciongrupoentidad>(0);
     private Set<Opciondeterminacion> opciondeterminacionsForIddeterminacion = new HashSet<Opciondeterminacion>(0);
     private Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacionoperadora = new HashSet<Operaciondeterminacion>(0);
     private Set<Opciondeterminacion> opciondeterminacionsForIddeterminacionvalorref = new HashSet<Opciondeterminacion>(0);
     private Set<Determinacion> determinacionsForIddeterminacionoriginal = new HashSet<Determinacion>(0);
     private Set<Determinacion> determinacionsForIddeterminacionbase = new HashSet<Determinacion>(0);
     private Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminacion = new HashSet<Determinaciongrupoentidad>(0);
     private Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacion = new HashSet<Operaciondeterminacion>(0);
     private Set<Entidaddeterminacionregimen> entidaddeterminacionregimens = new HashSet<Entidaddeterminacionregimen>(0);
     private Set<Entidaddeterminacion> entidaddeterminacions = new HashSet<Entidaddeterminacion>(0);
     private String apartadoCompleto;

    public Determinacion() {
    }


    public Determinacion(int iden, Tramite tramite, int idcaracter, String nombre, String codigo, boolean bsuspendida, int orden) {
        this.iden = iden;
        this.tramite = tramite;
        this.idcaracter = idcaracter;
        this.nombre = nombre;
        this.codigo = codigo;
        this.bsuspendida = bsuspendida;
        this.orden = orden;
    }

    public Determinacion(int iden, Tramite tramite, Determinacion determinacionByIddeterminacionoriginal, Determinacion determinacionByIddeterminacionbase, Determinacion determinacionByIdpadre, int idcaracter, String apartado, String nombre, String texto, String etiqueta, String codigo, boolean bsuspendida, int orden, Set<Documentodeterminacion> documentodeterminacions, Set<Determinacion> determinacionsForIdpadre, Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminaciongrupo, Set<Opciondeterminacion> opciondeterminacionsForIddeterminacion, Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacionoperadora, Set<Opciondeterminacion> opciondeterminacionsForIddeterminacionvalorref, Set<Determinacion> determinacionsForIddeterminacionoriginal, Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminacion, Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacion, Set<Entidaddeterminacionregimen> entidaddeterminacionregimens, Set<Entidaddeterminacion> entidaddeterminacions,Set<Determinacion> determinacionsForIddeterminacionbase) {

       this.iden = iden;
       this.tramite = tramite;
       this.determinacionByIddeterminacionoriginal = determinacionByIddeterminacionoriginal;
       this.determinacionByIddeterminacionbase = determinacionByIddeterminacionbase;
       this.determinacionByIdpadre = determinacionByIdpadre;
       this.idcaracter = idcaracter;
       this.apartado = apartado;
       this.nombre = nombre;
       this.texto = texto;
       this.etiqueta = etiqueta;
       this.codigo = codigo;
       this.bsuspendida = bsuspendida;
       this.orden = orden;
       this.documentodeterminacions = documentodeterminacions;
       this.determinacionsForIdpadre = determinacionsForIdpadre;
       this.determinaciongrupoentidadsForIddeterminaciongrupo = determinaciongrupoentidadsForIddeterminaciongrupo;
       this.opciondeterminacionsForIddeterminacion = opciondeterminacionsForIddeterminacion;
       this.operaciondeterminacionsForIddeterminacionoperadora = operaciondeterminacionsForIddeterminacionoperadora;
       this.opciondeterminacionsForIddeterminacionvalorref = opciondeterminacionsForIddeterminacionvalorref;
       this.determinacionsForIddeterminacionoriginal = determinacionsForIddeterminacionoriginal;
       this.determinacionsForIddeterminacionbase = determinacionsForIddeterminacionbase;
       this.determinaciongrupoentidadsForIddeterminacion = determinaciongrupoentidadsForIddeterminacion;
       this.operaciondeterminacionsForIddeterminacion = operaciondeterminacionsForIddeterminacion;
       this.entidaddeterminacionregimens = entidaddeterminacionregimens;
       this.entidaddeterminacions = entidaddeterminacions;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }
    public Tramite getTramite() {
        return this.tramite;
    }

    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }
    public Determinacion getDeterminacionByIddeterminacionoriginal() {
        return this.determinacionByIddeterminacionoriginal;
    }

    public void setDeterminacionByIddeterminacionoriginal(Determinacion determinacionByIddeterminacionoriginal) {
        this.determinacionByIddeterminacionoriginal = determinacionByIddeterminacionoriginal;
    }

    public Determinacion getDeterminacionByIddeterminacionbase() {
        return this.determinacionByIddeterminacionbase;
    }

    public void setDeterminacionByIddeterminacionbase(Determinacion determinacionByIddeterminacionbase) {
        this.determinacionByIddeterminacionbase = determinacionByIddeterminacionbase;
    }

    public Determinacion getDeterminacionByIdpadre() {
        return this.determinacionByIdpadre;
    }

    public void setDeterminacionByIdpadre(Determinacion determinacionByIdpadre) {
        this.determinacionByIdpadre = determinacionByIdpadre;
    }
    public int getIdcaracter() {
        return this.idcaracter;
    }

    public void setIdcaracter(int idcaracter) {
        this.idcaracter = idcaracter;
    }
    public String getApartado() {
        return this.apartado;
    }

    public void setApartado(String apartado) {
        this.apartado = apartado;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public String getEtiqueta() {
        return this.etiqueta;
    }

    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public boolean isBsuspendida() {
        return this.bsuspendida;
    }

    public void setBsuspendida(boolean bsuspendida) {
        this.bsuspendida = bsuspendida;
    }

    public String getApartadoCompleto() {
        return this.apartadoCompleto;
    }

    public void setApartadoCompleto(String apartadoCompleto) {
        this.apartadoCompleto = apartadoCompleto;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }
    public Set<Documentodeterminacion> getDocumentodeterminacions() {
       return this.documentodeterminacions;
    }

    public void setDocumentodeterminacions(Set<Documentodeterminacion> documentodeterminacions) {
        this.documentodeterminacions = documentodeterminacions;
    }
    public Set<Determinacion> getDeterminacionsForIdpadre() {
        return this.determinacionsForIdpadre;
    }

    public void setDeterminacionsForIdpadre(Set<Determinacion> determinacionsForIdpadre) {
        this.determinacionsForIdpadre = determinacionsForIdpadre;
    }
    public Set<Determinaciongrupoentidad> getDeterminaciongrupoentidadsForIddeterminaciongrupo() {
        return this.determinaciongrupoentidadsForIddeterminaciongrupo;
    }

    public void setDeterminaciongrupoentidadsForIddeterminaciongrupo(Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminaciongrupo) {
        this.determinaciongrupoentidadsForIddeterminaciongrupo = determinaciongrupoentidadsForIddeterminaciongrupo;
    }
    public Set<Opciondeterminacion> getOpciondeterminacionsForIddeterminacion() {
        return this.opciondeterminacionsForIddeterminacion;
    }

    public void setOpciondeterminacionsForIddeterminacion(Set<Opciondeterminacion> opciondeterminacionsForIddeterminacion) {
        this.opciondeterminacionsForIddeterminacion = opciondeterminacionsForIddeterminacion;
    }
    public Set<Operaciondeterminacion> getOperaciondeterminacionsForIddeterminacionoperadora() {
        return this.operaciondeterminacionsForIddeterminacionoperadora;
    }

    public void setOperaciondeterminacionsForIddeterminacionoperadora(Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacionoperadora) {
        this.operaciondeterminacionsForIddeterminacionoperadora = operaciondeterminacionsForIddeterminacionoperadora;
    }
    public Set<Opciondeterminacion> getOpciondeterminacionsForIddeterminacionvalorref() {
        return this.opciondeterminacionsForIddeterminacionvalorref;
    }

    public void setOpciondeterminacionsForIddeterminacionvalorref(Set<Opciondeterminacion> opciondeterminacionsForIddeterminacionvalorref) {
        this.opciondeterminacionsForIddeterminacionvalorref = opciondeterminacionsForIddeterminacionvalorref;
    }
    public Set<Determinacion> getDeterminacionsForIddeterminacionoriginal() {
        return this.determinacionsForIddeterminacionoriginal;
    }

    public void setDeterminacionsForIddeterminacionoriginal(Set<Determinacion> determinacionsForIddeterminacionoriginal) {
        this.determinacionsForIddeterminacionoriginal = determinacionsForIddeterminacionoriginal;
    }

    public Set<Determinacion> getDeterminacionsForIddeterminacionbase() {
        return this.determinacionsForIddeterminacionbase;
    }

    public void setDeterminacionsForIddeterminacionbase(Set<Determinacion> determinacionsForIddeterminacionbase) {
        this.determinacionsForIddeterminacionbase = determinacionsForIddeterminacionbase;
    }

    public Set<Determinaciongrupoentidad> getDeterminaciongrupoentidadsForIddeterminacion() {
        return this.determinaciongrupoentidadsForIddeterminacion;
    }

    public void setDeterminaciongrupoentidadsForIddeterminacion(Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminacion) {
        this.determinaciongrupoentidadsForIddeterminacion = determinaciongrupoentidadsForIddeterminacion;
    }
    public Set<Operaciondeterminacion> getOperaciondeterminacionsForIddeterminacion() {
        return this.operaciondeterminacionsForIddeterminacion;
    }

    public void setOperaciondeterminacionsForIddeterminacion(Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacion) {
        this.operaciondeterminacionsForIddeterminacion = operaciondeterminacionsForIddeterminacion;
    }
    public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimens() {
        return this.entidaddeterminacionregimens;
    }

    public void setEntidaddeterminacionregimens(Set<Entidaddeterminacionregimen> entidaddeterminacionregimens) {
        this.entidaddeterminacionregimens = entidaddeterminacionregimens;
    }
    public Set<Entidaddeterminacion> getEntidaddeterminacions() {
        return this.entidaddeterminacions;
    }

    public void setEntidaddeterminacions(Set<Entidaddeterminacion> entidaddeterminacions) {
        this.entidaddeterminacions = entidaddeterminacions;
    }
}
