/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Entidaddeterminacion generated by hbm2java
 */
public class Entidaddeterminacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8733650855340028766L;
	private int iden;
     private Entidad entidad;
     private Determinacion determinacion;
     private Set<Casoentidaddeterminacion> casoentidaddeterminacions = new HashSet<Casoentidaddeterminacion>(0);

    public Entidaddeterminacion() {
    }

	
    public Entidaddeterminacion(int iden, Entidad entidad, Determinacion determinacion) {
        this.iden = iden;
        this.entidad = entidad;
        this.determinacion = determinacion;
    }
    public Entidaddeterminacion(int iden, Entidad entidad, Determinacion determinacion, Set<Casoentidaddeterminacion> casoentidaddeterminacions) {
       this.iden = iden;
       this.entidad = entidad;
       this.determinacion = determinacion;
       this.casoentidaddeterminacions = casoentidaddeterminacions;
    }

    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public Determinacion getDeterminacion() {
        return this.determinacion;
    }
    
    public void setDeterminacion(Determinacion determinacion) {
        this.determinacion = determinacion;
    }
    public Set<Casoentidaddeterminacion> getCasoentidaddeterminacions() {
        return this.casoentidaddeterminacions;
    }
    
    public void setCasoentidaddeterminacions(Set<Casoentidaddeterminacion> casoentidaddeterminacions) {
        this.casoentidaddeterminacions = casoentidaddeterminacions;
    }




}


