/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;

import java.util.HashSet;
import java.util.Set;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

/**
 * Opciondeterminacion generated by hbm2java
 */
public class Opciondeterminacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6688624003412838035L;
	private int iden;
    private Determinacion determinacionByIddeterminacion;
    private Determinacion determinacionByIddeterminacionvalorref;
    private Set<Entidaddeterminacionregimen> entidaddeterminacionregimens = new HashSet<Entidaddeterminacionregimen>(0);
    

    public Opciondeterminacion() {
    }

	
    public Opciondeterminacion(int iden, Determinacion determinacionByIddeterminacion, Determinacion determinacionByIddeterminacionvalorref) {
        this.iden = iden;
        this.determinacionByIddeterminacion = determinacionByIddeterminacion;
        this.determinacionByIddeterminacionvalorref = determinacionByIddeterminacionvalorref;
    }

   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Determinacion getDeterminacionByIddeterminacion() {
        return this.determinacionByIddeterminacion;
    }
    
    public void setDeterminacionByIddeterminacion(Determinacion determinacionByIddeterminacion) {
        this.determinacionByIddeterminacion = determinacionByIddeterminacion;
    }
    public Determinacion getDeterminacionByIddeterminacionvalorref() {
        determinacionByIddeterminacionvalorref.getNombre();
        return this.determinacionByIddeterminacionvalorref;
    }
    
    public void setDeterminacionByIddeterminacionvalorref(Determinacion determinacionByIddeterminacionvalorref) {
        this.determinacionByIddeterminacionvalorref = determinacionByIddeterminacionvalorref;
    }

    public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimens() {
		return this.entidaddeterminacionregimens;
	}

	public void setEntidaddeterminacionregimens(
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimens) {
		this.entidaddeterminacionregimens = entidaddeterminacionregimens;
	}


}


