/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA



/**
 * Propiedadrelacion generated by hbm2java
 */
public class Propiedadrelacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4574581266761086744L;
	private int iden;
     private Relacion relacion;
     private int iddefpropiedad;
     private String valor;

    public Propiedadrelacion() {
    }

    public Propiedadrelacion(int iden, Relacion relacion, int iddefpropiedad, String valor) {
       this.iden = iden;
       this.relacion = relacion;
       this.iddefpropiedad = iddefpropiedad;
       this.valor = valor;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Relacion getRelacion() {
        return this.relacion;
    }
    
    public void setRelacion(Relacion relacion) {
        this.relacion = relacion;
    }
    public int getIddefpropiedad() {
        return this.iddefpropiedad;
    }
    
    public void setIddefpropiedad(int iddefpropiedad) {
        this.iddefpropiedad = iddefpropiedad;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


