/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Regimenespecifico generated by hbm2java
 */
public class Regimenespecifico  implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6969915581946449802L;

     private int iden;
     private Entidaddeterminacionregimen entidaddeterminacionregimen;
     private Regimenespecifico regimenespecifico;
     private int orden;
     private String nombre;
     private String texto;
     private Set<Regimenespecifico> regimenespecificos = new HashSet<Regimenespecifico>(0);

    public Regimenespecifico() {
    }

	
    public Regimenespecifico(int iden, Entidaddeterminacionregimen entidaddeterminacionregimen, int orden) {
        this.iden = iden;
        this.entidaddeterminacionregimen = entidaddeterminacionregimen;
        this.orden = orden;
    }
    public Regimenespecifico(int iden, Entidaddeterminacionregimen entidaddeterminacionregimen, Regimenespecifico regimenespecifico, int orden, String nombre, String texto, Set<Regimenespecifico> regimenespecificos) {
       this.iden = iden;
       this.entidaddeterminacionregimen = entidaddeterminacionregimen;
       this.regimenespecifico = regimenespecifico;
       this.orden = orden;
       this.nombre = nombre;
       this.texto = texto;
       this.regimenespecificos = regimenespecificos;
    }

    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Entidaddeterminacionregimen getEntidaddeterminacionregimen() {
        return this.entidaddeterminacionregimen;
    }
    
    public void setEntidaddeterminacionregimen(Entidaddeterminacionregimen entidaddeterminacionregimen) {
        this.entidaddeterminacionregimen = entidaddeterminacionregimen;
    }
    public Regimenespecifico getRegimenespecifico() {
        return this.regimenespecifico;
    }
    
    public void setRegimenespecifico(Regimenespecifico regimenespecifico) {
        this.regimenespecifico = regimenespecifico;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Set<Regimenespecifico> getRegimenespecificos() {
        return this.regimenespecificos;
    }
    
    public void setRegimenespecificos(Set<Regimenespecifico> regimenespecificos) {
        this.regimenespecificos = regimenespecificos;
    }

}
