package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Casoentidaddeterminacion generated by hbm2java
 */
@Entity
@Table(name = "casoentidaddeterminacion")
public class Casoentidaddeterminacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -105412861062392903L;
	private int iden;
	private Entidaddeterminacion entidaddeterminacion;
	private String nombre;
	private int orden;
	private Set<Documentocaso> documentocasos = new HashSet<Documentocaso>(0);
	private Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcaso = new HashSet<Entidaddeterminacionregimen>(
			0);
	private Set<Vinculocaso> vinculocasosForIdcaso = new HashSet<Vinculocaso>(0);
	private Set<Vinculocaso> vinculocasosForIdcasovinculado = new HashSet<Vinculocaso>(
			0);
	private Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcasoaplicacion = new HashSet<Entidaddeterminacionregimen>(
			0);

	public Casoentidaddeterminacion() {
	}

	public Casoentidaddeterminacion(int iden,
			Entidaddeterminacion entidaddeterminacion, int orden) {
		this.iden = iden;
		this.entidaddeterminacion = entidaddeterminacion;
		this.orden = orden;
	}

	public Casoentidaddeterminacion(
			int iden,
			Entidaddeterminacion entidaddeterminacion,
			String nombre,
			int orden,
			Set<Documentocaso> documentocasos,
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcaso,
			Set<Vinculocaso> vinculocasosForIdcaso,
			Set<Vinculocaso> vinculocasosForIdcasovinculado,
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcasoaplicacion) {
		this.iden = iden;
		this.entidaddeterminacion = entidaddeterminacion;
		this.nombre = nombre;
		this.orden = orden;
		this.documentocasos = documentocasos;
		this.entidaddeterminacionregimensForIdcaso = entidaddeterminacionregimensForIdcaso;
		this.vinculocasosForIdcaso = vinculocasosForIdcaso;
		this.vinculocasosForIdcasovinculado = vinculocasosForIdcasovinculado;
		this.entidaddeterminacionregimensForIdcasoaplicacion = entidaddeterminacionregimensForIdcasoaplicacion;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identidaddeterminacion", nullable = false)
	public Entidaddeterminacion getEntidaddeterminacion() {
		return this.entidaddeterminacion;
	}

	public void setEntidaddeterminacion(
			Entidaddeterminacion entidaddeterminacion) {
		this.entidaddeterminacion = entidaddeterminacion;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoentidaddeterminacion")
	public Set<Documentocaso> getDocumentocasos() {
		return this.documentocasos;
	}

	public void setDocumentocasos(Set<Documentocaso> documentocasos) {
		this.documentocasos = documentocasos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoentidaddeterminacionByIdcaso")
	public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimensForIdcaso() {
		return this.entidaddeterminacionregimensForIdcaso;
	}

	public void setEntidaddeterminacionregimensForIdcaso(
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcaso) {
		this.entidaddeterminacionregimensForIdcaso = entidaddeterminacionregimensForIdcaso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoentidaddeterminacionByIdcaso")
	public Set<Vinculocaso> getVinculocasosForIdcaso() {
		return this.vinculocasosForIdcaso;
	}

	public void setVinculocasosForIdcaso(Set<Vinculocaso> vinculocasosForIdcaso) {
		this.vinculocasosForIdcaso = vinculocasosForIdcaso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoentidaddeterminacionByIdcasovinculado")
	public Set<Vinculocaso> getVinculocasosForIdcasovinculado() {
		return this.vinculocasosForIdcasovinculado;
	}

	public void setVinculocasosForIdcasovinculado(
			Set<Vinculocaso> vinculocasosForIdcasovinculado) {
		this.vinculocasosForIdcasovinculado = vinculocasosForIdcasovinculado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casoentidaddeterminacionByIdcasoaplicacion")
	public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimensForIdcasoaplicacion() {
		return this.entidaddeterminacionregimensForIdcasoaplicacion;
	}

	public void setEntidaddeterminacionregimensForIdcasoaplicacion(
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcasoaplicacion) {
		this.entidaddeterminacionregimensForIdcasoaplicacion = entidaddeterminacionregimensForIdcasoaplicacion;
	}

}
