//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Código universal de una condición urbanística vinculando el código universal de una determinación con el código universal de una entidad sobre la que se aplica.
 * 
 * <p>Java class for CodigoCondicionUrbanistica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodigoCondicionUrbanistica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ENTIDAD" type="{}CodigoEntidad"/>
 *         &lt;element name="DETERMINACION" type="{}CodigoDeterminacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodigoCondicionUrbanistica", propOrder = {
    "entidad",
    "determinacion"
})
public class CodigoCondicionUrbanistica {

    @XmlElement(name = "ENTIDAD", required = true)
    protected CodigoEntidad entidad;
    @XmlElement(name = "DETERMINACION", required = true)
    protected CodigoDeterminacion determinacion;

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoEntidad }
     *     
     */
    public CodigoEntidad getENTIDAD() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoEntidad }
     *     
     */
    public void setENTIDAD(CodigoEntidad value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the determinacion property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getDETERMINACION() {
        return determinacion;
    }

    /**
     * Sets the value of the determinacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setDETERMINACION(CodigoDeterminacion value) {
        this.determinacion = value;
    }

}
