//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Indica, para cada tipo de operación, el carócter de las determinaciones que pueden entrar a formar parte de la misma como operadora y operadora
 * 
 * <p>Java class for OperacionCaracter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperacionCaracter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TipoOperacionDeterminacion" use="required" type="{}IdentificadorTipoOperacionDeterminacion" />
 *       &lt;attribute name="CaracterOperadora" use="required" type="{}IdentificadorCaracterDeterminacion" />
 *       &lt;attribute name="CaracterOperada" use="required" type="{}IdentificadorCaracterDeterminacion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperacionCaracter")
public class OperacionCaracter {

    @XmlAttribute(name = "TipoOperacionDeterminacion", required = true)
    protected String tipoOperacionDeterminacion;
    @XmlAttribute(name = "CaracterOperadora", required = true)
    protected String caracterOperadora;
    @XmlAttribute(name = "CaracterOperada", required = true)
    protected String caracterOperada;

    /**
     * Gets the value of the tipoOperacionDeterminacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoOperacionDeterminacion() {
        return tipoOperacionDeterminacion;
    }

    /**
     * Sets the value of the tipoOperacionDeterminacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoOperacionDeterminacion(String value) {
        this.tipoOperacionDeterminacion = value;
    }

    /**
     * Gets the value of the caracterOperadora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaracterOperadora() {
        return caracterOperadora;
    }

    /**
     * Sets the value of the caracterOperadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaracterOperadora(String value) {
        this.caracterOperadora = value;
    }

    /**
     * Gets the value of the caracterOperada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaracterOperada() {
        return caracterOperada;
    }

    /**
     * Sets the value of the caracterOperada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaracterOperada(String value) {
        this.caracterOperada = value;
    }

}
