//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Una adscripción es una relación entre dos entidades con contenido informativo.
 * Esta relación se define como una operación con propiedes extra que aporta este tipo complejo.
 * 
 * <p>Java class for PropiedadesAdscripcion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropiedadesAdscripcion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UNIDAD" type="{}CodigoDeterminacion"/>
 *         &lt;element name="TIPO" type="{}CodigoDeterminacion"/>
 *         &lt;element name="TEXTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cuantia" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropiedadesAdscripcion", propOrder = {
    "unidad",
    "tipo",
    "texto"
})
public class PropiedadesAdscripcion {

    @XmlElement(name = "UNIDAD", required = true)
    protected CodigoDeterminacion unidad;
    @XmlElement(name = "TIPO", required = true)
    protected CodigoDeterminacion tipo;
    @XmlElement(name = "TEXTO")
    protected String texto;
    @XmlAttribute(name = "cuantia", required = true)
    protected double cuantia;

    /**
     * Gets the value of the unidad property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getUNIDAD() {
        return unidad;
    }

    /**
     * Sets the value of the unidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setUNIDAD(CodigoDeterminacion value) {
        this.unidad = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getTIPO() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setTIPO(CodigoDeterminacion value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the cuantia property.
     * 
     */
    public double getCuantia() {
        return cuantia;
    }

    /**
     * Sets the value of the cuantia property.
     * 
     */
    public void setCuantia(double value) {
        this.cuantia = value;
    }

}
