//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Trómite sufrido por un plan
 * 
 * <p>Java class for Tramite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tramite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TEXTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DOCUMENTOS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DOCUMENTO" type="{}Documento" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="DOCUMENTO-REFUNDIDO" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" type="{}IdentificadorDocumento" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ENTIDADES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ENTIDAD" type="{}Entidad" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DETERMINACIONES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DETERMINACION" type="{}Determinacion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CONDICIONES-URBANISTICAS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CONDICION-URBANISTICA" type="{}CondicionUrbanistica" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OPERACIONES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OPERACIONES-DETERMINACIONES" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OPERACION-DETERMINACION" type="{}OperacionDeterminacion" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OPERACIONES-ENTIDADES" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OPERACION-ENTIDAD" type="{}OperacionEntidad" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UNIDADES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UNIDAD" type="{}Unidad" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="APLICACION-AMBITOS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="APLICACION-AMBITO" type="{}AplicacionAmbito" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ADSCRIPCIONES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ADSCRIPCION" type="{}Adscripcion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="tipoTramite" use="required" type="{}IdentificadorTipoTramite" />
 *       &lt;attribute name="codigo" use="required" type="{}IdentificadorTramite" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tramite", propOrder = {
    "texto",
    "documentos",
    "entidades",
    "determinaciones",
    "condicionesurbanisticas",
    "operaciones",
    "unidades",
    "aplicacionambitos",
    "adscripciones"
})
public class Tramite {

    @XmlElement(name = "TEXTO")
    protected String texto;
    @XmlElement(name = "DOCUMENTOS")
    protected Tramite.DOCUMENTOS documentos;
    @XmlElement(name = "ENTIDADES", required = true)
    protected Tramite.ENTIDADES entidades;
    @XmlElement(name = "DETERMINACIONES", required = true)
    protected Tramite.DETERMINACIONES determinaciones;
    @XmlElement(name = "CONDICIONES-URBANISTICAS")
    protected Tramite.CONDICIONESURBANISTICAS condicionesurbanisticas;
    @XmlElement(name = "OPERACIONES")
    protected Tramite.OPERACIONES operaciones;
    @XmlElement(name = "UNIDADES")
    protected Tramite.UNIDADES unidades;
    @XmlElement(name = "APLICACION-AMBITOS")
    protected Tramite.APLICACIONAMBITOS aplicacionambitos;
    @XmlElement(name = "ADSCRIPCIONES")
    protected Tramite.ADSCRIPCIONES adscripciones;
    @XmlAttribute(name = "tipoTramite", required = true)
    protected String tipoTramite;
    @XmlAttribute(name = "codigo", required = true)
    protected String codigo;

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the documentos property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.DOCUMENTOS }
     *     
     */
    public Tramite.DOCUMENTOS getDOCUMENTOS() {
        return documentos;
    }

    /**
     * Sets the value of the documentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.DOCUMENTOS }
     *     
     */
    public void setDOCUMENTOS(Tramite.DOCUMENTOS value) {
        this.documentos = value;
    }

    /**
     * Gets the value of the entidades property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.ENTIDADES }
     *     
     */
    public Tramite.ENTIDADES getENTIDADES() {
        return entidades;
    }

    /**
     * Sets the value of the entidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.ENTIDADES }
     *     
     */
    public void setENTIDADES(Tramite.ENTIDADES value) {
        this.entidades = value;
    }

    /**
     * Gets the value of the determinaciones property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.DETERMINACIONES }
     *     
     */
    public Tramite.DETERMINACIONES getDETERMINACIONES() {
        return determinaciones;
    }

    /**
     * Sets the value of the determinaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.DETERMINACIONES }
     *     
     */
    public void setDETERMINACIONES(Tramite.DETERMINACIONES value) {
        this.determinaciones = value;
    }

    /**
     * Gets the value of the condicionesurbanisticas property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.CONDICIONESURBANISTICAS }
     *     
     */
    public Tramite.CONDICIONESURBANISTICAS getCONDICIONESURBANISTICAS() {
        return condicionesurbanisticas;
    }

    /**
     * Sets the value of the condicionesurbanisticas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.CONDICIONESURBANISTICAS }
     *     
     */
    public void setCONDICIONESURBANISTICAS(Tramite.CONDICIONESURBANISTICAS value) {
        this.condicionesurbanisticas = value;
    }

    /**
     * Gets the value of the operaciones property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.OPERACIONES }
     *     
     */
    public Tramite.OPERACIONES getOPERACIONES() {
        return operaciones;
    }

    /**
     * Sets the value of the operaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.OPERACIONES }
     *     
     */
    public void setOPERACIONES(Tramite.OPERACIONES value) {
        this.operaciones = value;
    }

    /**
     * Gets the value of the unidades property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.UNIDADES }
     *     
     */
    public Tramite.UNIDADES getUNIDADES() {
        return unidades;
    }

    /**
     * Sets the value of the unidades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.UNIDADES }
     *     
     */
    public void setUNIDADES(Tramite.UNIDADES value) {
        this.unidades = value;
    }

    /**
     * Gets the value of the aplicacionambitos property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.APLICACIONAMBITOS }
     *     
     */
    public Tramite.APLICACIONAMBITOS getAPLICACIONAMBITOS() {
        return aplicacionambitos;
    }

    /**
     * Sets the value of the aplicacionambitos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.APLICACIONAMBITOS }
     *     
     */
    public void setAPLICACIONAMBITOS(Tramite.APLICACIONAMBITOS value) {
        this.aplicacionambitos = value;
    }

    /**
     * Gets the value of the adscripciones property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite.ADSCRIPCIONES }
     *     
     */
    public Tramite.ADSCRIPCIONES getADSCRIPCIONES() {
        return adscripciones;
    }

    /**
     * Sets the value of the adscripciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite.ADSCRIPCIONES }
     *     
     */
    public void setADSCRIPCIONES(Tramite.ADSCRIPCIONES value) {
        this.adscripciones = value;
    }

    /**
     * Gets the value of the tipoTramite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTramite() {
        return tipoTramite;
    }

    /**
     * Sets the value of the tipoTramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTramite(String value) {
        this.tipoTramite = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ADSCRIPCION" type="{}Adscripcion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adscripcion"
    })
    public static class ADSCRIPCIONES {

        @XmlElement(name = "ADSCRIPCION", required = true)
        protected List<Adscripcion> adscripcion;

        /**
         * Gets the value of the adscripcion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the adscripcion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getADSCRIPCION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Adscripcion }
         * 
         * 
         */
        public List<Adscripcion> getADSCRIPCION() {
            if (adscripcion == null) {
                adscripcion = new ArrayList<Adscripcion>();
            }
            return this.adscripcion;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="APLICACION-AMBITO" type="{}AplicacionAmbito" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aplicacionambito"
    })
    public static class APLICACIONAMBITOS {

        @XmlElement(name = "APLICACION-AMBITO", required = true)
        protected List<AplicacionAmbito> aplicacionambito;

        /**
         * Gets the value of the aplicacionambito property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aplicacionambito property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAPLICACIONAMBITO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AplicacionAmbito }
         * 
         * 
         */
        public List<AplicacionAmbito> getAPLICACIONAMBITO() {
            if (aplicacionambito == null) {
                aplicacionambito = new ArrayList<AplicacionAmbito>();
            }
            return this.aplicacionambito;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CONDICION-URBANISTICA" type="{}CondicionUrbanistica" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "condicionurbanistica"
    })
    public static class CONDICIONESURBANISTICAS {

        @XmlElement(name = "CONDICION-URBANISTICA", required = true)
        protected List<CondicionUrbanistica> condicionurbanistica;

        /**
         * Gets the value of the condicionurbanistica property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the condicionurbanistica property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCONDICIONURBANISTICA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CondicionUrbanistica }
         * 
         * 
         */
        public List<CondicionUrbanistica> getCONDICIONURBANISTICA() {
            if (condicionurbanistica == null) {
                condicionurbanistica = new ArrayList<CondicionUrbanistica>();
            }
            return this.condicionurbanistica;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DETERMINACION" type="{}Determinacion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "determinacion"
    })
    public static class DETERMINACIONES {

        @XmlElement(name = "DETERMINACION", required = true)
        protected List<Determinacion> determinacion;

        /**
         * Gets the value of the determinacion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the determinacion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDETERMINACION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Determinacion }
         * 
         * 
         */
        public List<Determinacion> getDETERMINACION() {
            if (determinacion == null) {
                determinacion = new ArrayList<Determinacion>();
            }
            return this.determinacion;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DOCUMENTO" type="{}Documento" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="DOCUMENTO-REFUNDIDO" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" type="{}IdentificadorDocumento" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documento",
        "documentorefundido"
    })
    public static class DOCUMENTOS {

        @XmlElement(name = "DOCUMENTO")
        protected List<Documento> documento;
        @XmlElement(name = "DOCUMENTO-REFUNDIDO")
        protected List<Tramite.DOCUMENTOS.DOCUMENTOREFUNDIDO> documentorefundido;

        /**
         * Gets the value of the documento property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documento property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDOCUMENTO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Documento }
         * 
         * 
         */
        public List<Documento> getDOCUMENTO() {
            if (documento == null) {
                documento = new ArrayList<Documento>();
            }
            return this.documento;
        }

        /**
         * Gets the value of the documentorefundido property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documentorefundido property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDOCUMENTOREFUNDIDO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tramite.DOCUMENTOS.DOCUMENTOREFUNDIDO }
         * 
         * 
         */
        public List<Tramite.DOCUMENTOS.DOCUMENTOREFUNDIDO> getDOCUMENTOREFUNDIDO() {
            if (documentorefundido == null) {
                documentorefundido = new ArrayList<Tramite.DOCUMENTOS.DOCUMENTOREFUNDIDO>();
            }
            return this.documentorefundido;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" type="{}IdentificadorDocumento" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DOCUMENTOREFUNDIDO {

            @XmlAttribute(name = "codigo")
            protected String codigo;

            /**
             * Gets the value of the codigo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ENTIDAD" type="{}Entidad" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entidad"
    })
    public static class ENTIDADES {

        @XmlElement(name = "ENTIDAD", required = true)
        protected List<Entidad> entidad;

        /**
         * Gets the value of the entidad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entidad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getENTIDAD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Entidad }
         * 
         * 
         */
        public List<Entidad> getENTIDAD() {
            if (entidad == null) {
                entidad = new ArrayList<Entidad>();
            }
            return this.entidad;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OPERACIONES-DETERMINACIONES" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OPERACION-DETERMINACION" type="{}OperacionDeterminacion" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OPERACIONES-ENTIDADES" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OPERACION-ENTIDAD" type="{}OperacionEntidad" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operacionesdeterminaciones",
        "operacionesentidades"
    })
    public static class OPERACIONES {

        @XmlElement(name = "OPERACIONES-DETERMINACIONES")
        protected List<Tramite.OPERACIONES.OPERACIONESDETERMINACIONES> operacionesdeterminaciones;
        @XmlElement(name = "OPERACIONES-ENTIDADES")
        protected List<Tramite.OPERACIONES.OPERACIONESENTIDADES> operacionesentidades;

        /**
         * Gets the value of the operacionesdeterminaciones property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operacionesdeterminaciones property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOPERACIONESDETERMINACIONES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tramite.OPERACIONES.OPERACIONESDETERMINACIONES }
         * 
         * 
         */
        public List<Tramite.OPERACIONES.OPERACIONESDETERMINACIONES> getOPERACIONESDETERMINACIONES() {
            if (operacionesdeterminaciones == null) {
                operacionesdeterminaciones = new ArrayList<Tramite.OPERACIONES.OPERACIONESDETERMINACIONES>();
            }
            return this.operacionesdeterminaciones;
        }

        /**
         * Gets the value of the operacionesentidades property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operacionesentidades property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOPERACIONESENTIDADES().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Tramite.OPERACIONES.OPERACIONESENTIDADES }
         * 
         * 
         */
        public List<Tramite.OPERACIONES.OPERACIONESENTIDADES> getOPERACIONESENTIDADES() {
            if (operacionesentidades == null) {
                operacionesentidades = new ArrayList<Tramite.OPERACIONES.OPERACIONESENTIDADES>();
            }
            return this.operacionesentidades;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OPERACION-DETERMINACION" type="{}OperacionDeterminacion" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "operaciondeterminacion"
        })
        public static class OPERACIONESDETERMINACIONES {

            @XmlElement(name = "OPERACION-DETERMINACION", required = true)
            protected List<OperacionDeterminacion> operaciondeterminacion;

            /**
             * Gets the value of the operaciondeterminacion property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the operaciondeterminacion property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOPERACIONDETERMINACION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OperacionDeterminacion }
             * 
             * 
             */
            public List<OperacionDeterminacion> getOPERACIONDETERMINACION() {
                if (operaciondeterminacion == null) {
                    operaciondeterminacion = new ArrayList<OperacionDeterminacion>();
                }
                return this.operaciondeterminacion;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OPERACION-ENTIDAD" type="{}OperacionEntidad" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "operacionentidad"
        })
        public static class OPERACIONESENTIDADES {

            @XmlElement(name = "OPERACION-ENTIDAD", required = true)
            protected List<OperacionEntidad> operacionentidad;

            /**
             * Gets the value of the operacionentidad property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the operacionentidad property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOPERACIONENTIDAD().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OperacionEntidad }
             * 
             * 
             */
            public List<OperacionEntidad> getOPERACIONENTIDAD() {
                if (operacionentidad == null) {
                    operacionentidad = new ArrayList<OperacionEntidad>();
                }
                return this.operacionentidad;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UNIDAD" type="{}Unidad" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unidad"
    })
    public static class UNIDADES {

        @XmlElement(name = "UNIDAD", required = true)
        protected List<Unidad> unidad;

        /**
         * Gets the value of the unidad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unidad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUNIDAD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Unidad }
         * 
         * 
         */
        public List<Unidad> getUNIDAD() {
            if (unidad == null) {
                unidad = new ArrayList<Unidad>();
            }
            return this.unidad;
        }

    }

}
