/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.explotacion;
// Generated 03-jul-2009 13:26:32 by Hibernate Tools 3.2.1.GA

/**
 * Capagrupo generated by hbm2java
 */
public class Capagrupo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6998462432627408860L;
	private int iden;
     private Capa capa;
     private int orden;
     private String codigodeterminaciongrupo;
     

    public Capagrupo() {
    }

	
    public Capagrupo(int iden, Capa capa, int orden, String codigodeterminaciongrupo) {
        this.iden = iden;
        this.capa = capa;
        this.orden = orden;
        this.codigodeterminaciongrupo = codigodeterminaciongrupo;
    }

   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Capa getCapa() {
        return this.capa;
    }
    
    public void setCapa(Capa capa) {
        this.capa = capa;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public String getCodigodeterminaciongrupo() {
        return this.codigodeterminaciongrupo;
    }
    
    public void setCodigodeterminaciongrupo(String codigodeterminaciongrupo) {
        this.codigodeterminaciongrupo = codigodeterminaciongrupo;
    }
   
}


