package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Documentodeterminacion generated by hbm2java
 */
@Entity
@Table(name = "documentodeterminacion")
public class Documentodeterminacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1868310171598713683L;
	private int iden;
	private Documento documento;
	private Determinacion determinacion;

	public Documentodeterminacion() {
	}

	public Documentodeterminacion(int iden, Documento documento,
			Determinacion determinacion) {
		this.iden = iden;
		this.documento = documento;
		this.determinacion = determinacion;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocumento", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminacion", nullable = false)
	public Determinacion getDeterminacion() {
		return this.determinacion;
	}

	public void setDeterminacion(Determinacion determinacion) {
		this.determinacion = determinacion;
	}

}
