package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vectorrelacion generated by hbm2java
 */
@Entity
@Table(name = "vectorrelacion")
public class Vectorrelacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3064977794165211255L;
	private int iden;
	private Relacion relacion;
	private int iddefvector;
	private int valor;

	public Vectorrelacion() {
	}

	public Vectorrelacion(int iden, Relacion relacion, int iddefvector,
			int valor) {
		this.iden = iden;
		this.relacion = relacion;
		this.iddefvector = iddefvector;
		this.valor = valor;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrelacion", nullable = false)
	public Relacion getRelacion() {
		return this.relacion;
	}

	public void setRelacion(Relacion relacion) {
		this.relacion = relacion;
	}

	@Column(name = "iddefvector", nullable = false)
	public int getIddefvector() {
		return this.iddefvector;
	}

	public void setIddefvector(int iddefvector) {
		this.iddefvector = iddefvector;
	}

	@Column(name = "valor", nullable = false)
	public int getValor() {
		return this.valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

}
