/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.explotacion;
// Generated 03-jul-2009 13:26:32 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Capa generated by hbm2java
 */
public class Capa  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7399879192636654591L;
	private int iden;
     private int orden;
     private String nombre;
     private Set<Capagrupo> capagrupos = new HashSet<Capagrupo>(0);
    

    public Capa() {
    }

	
    public Capa(int iden, String nombre, int orden) {
        this.iden = iden;
        this.orden = orden;
        this.nombre = nombre;
    }
   
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
 
    public Set<Capagrupo> getCapagrupos() {
        return this.capagrupos;
    }
    
    public void setCapagrupos(Set<Capagrupo> capagrupos) {
        this.capagrupos = capagrupos;
    }
   



}


