//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Una condición urbanóstica representa la aplicación de una determinación sobre una entidad
 * 
 * <p>Java class for CondicionUrbanistica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CondicionUrbanistica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CODIGO" type="{}CodigoCondicionUrbanistica"/>
 *         &lt;element name="CASOS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CASO" type="{}Caso" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CondicionUrbanistica", propOrder = {
    "codigo",
    "casos"
})
public class CondicionUrbanistica {

    @XmlElement(name = "CODIGO", required = true)
    protected CodigoCondicionUrbanistica codigo;
    @XmlElement(name = "CASOS", required = true)
    protected CondicionUrbanistica.CASOS casos;

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoCondicionUrbanistica }
     *     
     */
    public CodigoCondicionUrbanistica getCODIGO() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoCondicionUrbanistica }
     *     
     */
    public void setCODIGO(CodigoCondicionUrbanistica value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the casos property.
     * 
     * @return
     *     possible object is
     *     {@link CondicionUrbanistica.CASOS }
     *     
     */
    public CondicionUrbanistica.CASOS getCASOS() {
        return casos;
    }

    /**
     * Sets the value of the casos property.
     * 
     * @param value
     *     allowed object is
     *     {@link CondicionUrbanistica.CASOS }
     *     
     */
    public void setCASOS(CondicionUrbanistica.CASOS value) {
        this.casos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CASO" type="{}Caso" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caso"
    })
    public static class CASOS {

        @XmlElement(name = "CASO", required = true)
        protected List<Caso> caso;

        /**
         * Gets the value of the caso property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the caso property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCASO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Caso }
         * 
         * 
         */
        public List<Caso> getCASO() {
            if (caso == null) {
                caso = new ArrayList<Caso>();
            }
            return this.caso;
        }

    }

}
