//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="DICCIONARIO" type="{}Diccionario"/>
 *           &lt;element name="CATALOGO-SISTEMATIZADO" type="{}PlanRegistrado" minOccurs="0"/>
 *           &lt;element name="PLANEAMIENTO-VIGENTE" type="{}PlanRegistrado" minOccurs="0"/>
 *           &lt;element name="PLANEAMIENTO-ENCARGADO" type="{}PlanDigital"/>
 *         &lt;/sequence>
 *         &lt;element name="TRAMITE" type="{}Tramite"/>
 *       &lt;/choice>
 *       &lt;attribute name="PAIS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="2"/>
 *             &lt;enumeration value="es"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FECHA" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SRS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "diccionario",
    "catalogosistematizado",
    "planeamientovigente",
    "planeamientoencargado",
    "tramite"
})
@XmlRootElement(name = "FIP")
public class FIP {

    @XmlElement(name = "DICCIONARIO")
    protected Diccionario diccionario;
    @XmlElement(name = "CATALOGO-SISTEMATIZADO")
    protected PlanRegistrado catalogosistematizado;
    @XmlElement(name = "PLANEAMIENTO-VIGENTE")
    protected PlanRegistrado planeamientovigente;
    @XmlElement(name = "PLANEAMIENTO-ENCARGADO")
    protected PlanDigital planeamientoencargado;
    @XmlElement(name = "TRAMITE")
    protected Tramite tramite;
    @XmlAttribute(name = "PAIS")
    protected String pais;
    @XmlAttribute(name = "FECHA")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fecha;
    @XmlAttribute(name = "VERSION")
    protected String version;
    @XmlAttribute(name = "SRS")
    protected String srs;

    /**
     * Gets the value of the diccionario property.
     * 
     * @return
     *     possible object is
     *     {@link Diccionario }
     *     
     */
    public Diccionario getDICCIONARIO() {
        return diccionario;
    }

    /**
     * Sets the value of the diccionario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Diccionario }
     *     
     */
    public void setDICCIONARIO(Diccionario value) {
        this.diccionario = value;
    }

    /**
     * Gets the value of the catalogosistematizado property.
     * 
     * @return
     *     possible object is
     *     {@link PlanRegistrado }
     *     
     */
    public PlanRegistrado getCATALOGOSISTEMATIZADO() {
        return catalogosistematizado;
    }

    /**
     * Sets the value of the catalogosistematizado property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanRegistrado }
     *     
     */
    public void setCATALOGOSISTEMATIZADO(PlanRegistrado value) {
        this.catalogosistematizado = value;
    }

    /**
     * Gets the value of the planeamientovigente property.
     * 
     * @return
     *     possible object is
     *     {@link PlanRegistrado }
     *     
     */
    public PlanRegistrado getPLANEAMIENTOVIGENTE() {
        return planeamientovigente;
    }

    /**
     * Sets the value of the planeamientovigente property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanRegistrado }
     *     
     */
    public void setPLANEAMIENTOVIGENTE(PlanRegistrado value) {
        this.planeamientovigente = value;
    }

    /**
     * Gets the value of the planeamientoencargado property.
     * 
     * @return
     *     possible object is
     *     {@link PlanDigital }
     *     
     */
    public PlanDigital getPLANEAMIENTOENCARGADO() {
        return planeamientoencargado;
    }

    /**
     * Sets the value of the planeamientoencargado property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanDigital }
     *     
     */
    public void setPLANEAMIENTOENCARGADO(PlanDigital value) {
        this.planeamientoencargado = value;
    }

    /**
     * Gets the value of the tramite property.
     * 
     * @return
     *     possible object is
     *     {@link Tramite }
     *     
     */
    public Tramite getTRAMITE() {
        return tramite;
    }

    /**
     * Sets the value of the tramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tramite }
     *     
     */
    public void setTRAMITE(Tramite value) {
        this.tramite = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAIS() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAIS(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFECHA() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFECHA(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the srs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRS() {
        return srs;
    }

    /**
     * Sets the value of the srs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRS(String value) {
        this.srs = value;
    }

}
