//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Operación entre determinaciones
 * 
 * <p>Java class for OperacionDeterminacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperacionDeterminacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OPERADA" type="{}CodigoDeterminacion"/>
 *         &lt;element name="OPERADORA" type="{}CodigoDeterminacion"/>
 *         &lt;element name="TEXTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tipo" use="required" type="{}IdentificadorTipoOperacionDeterminacion" />
 *       &lt;attribute name="orden" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperacionDeterminacion", propOrder = {
    "operada",
    "operadora",
    "texto"
})
public class OperacionDeterminacion {

    @XmlElement(name = "OPERADA", required = true)
    protected CodigoDeterminacion operada;
    @XmlElement(name = "OPERADORA", required = true)
    protected CodigoDeterminacion operadora;
    @XmlElement(name = "TEXTO")
    protected String texto;
    @XmlAttribute(name = "tipo", required = true)
    protected String tipo;
    @XmlAttribute(name = "orden", required = true)
    protected long orden;

    /**
     * Gets the value of the operada property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getOPERADA() {
        return operada;
    }

    /**
     * Sets the value of the operada property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setOPERADA(CodigoDeterminacion value) {
        this.operada = value;
    }

    /**
     * Gets the value of the operadora property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getOPERADORA() {
        return operadora;
    }

    /**
     * Sets the value of the operadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setOPERADORA(CodigoDeterminacion value) {
        this.operadora = value;
    }

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the orden property.
     * 
     */
    public long getOrden() {
        return orden;
    }

    /**
     * Sets the value of the orden property.
     * 
     */
    public void setOrden(long value) {
        this.orden = value;
    }

}
