//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Matizaciones del valor con condiciones normativas que pueden llegar a ser un texto extenso, por este motivo el Rógimen especófico puede estructurarse en carpetas (definidas por la recursividad HIJOS).
 * 
 * 
 * <p>Java class for RegimenEspecifico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegimenEspecifico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TEXTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HIJOS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="REGIMEN-ESPECIFICO" type="{}RegimenEspecifico" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="orden" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegimenEspecifico", propOrder = {
    "texto",
    "hijos"
})
public class RegimenEspecifico {

    @XmlElement(name = "TEXTO")
    protected String texto;
    @XmlElement(name = "HIJOS")
    protected RegimenEspecifico.HIJOS hijos;
    @XmlAttribute(name = "orden", required = true)
    protected BigInteger orden;
    @XmlAttribute(name = "nombre", required = true)
    protected String nombre;

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the hijos property.
     * 
     * @return
     *     possible object is
     *     {@link RegimenEspecifico.HIJOS }
     *     
     */
    public RegimenEspecifico.HIJOS getHIJOS() {
        return hijos;
    }

    /**
     * Sets the value of the hijos property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegimenEspecifico.HIJOS }
     *     
     */
    public void setHIJOS(RegimenEspecifico.HIJOS value) {
        this.hijos = value;
    }

    /**
     * Gets the value of the orden property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrden() {
        return orden;
    }

    /**
     * Sets the value of the orden property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrden(BigInteger value) {
        this.orden = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="REGIMEN-ESPECIFICO" type="{}RegimenEspecifico" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regimenespecifico"
    })
    public static class HIJOS {

        @XmlElement(name = "REGIMEN-ESPECIFICO", required = true)
        protected List<RegimenEspecifico> regimenespecifico;

        /**
         * Gets the value of the regimenespecifico property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the regimenespecifico property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getREGIMENESPECIFICO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RegimenEspecifico }
         * 
         * 
         */
        public List<RegimenEspecifico> getREGIMENESPECIFICO() {
            if (regimenespecifico == null) {
                regimenespecifico = new ArrayList<RegimenEspecifico>();
            }
            return this.regimenespecifico;
        }

    }

}
