//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Cada uno de los atributos que un trómite puede asignar a cada entidad segón el grupo al que ósta pertenezca.
 * Cada trómite puede crear su propio católogo de Determinaciones
 * 
 * <p>Java class for Determinacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Determinacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TEXTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VALORES-REFERENCIA" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VALOR-REFERENCIA" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HIJAS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DETERMINACION" type="{}Determinacion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DOCUMENTOS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DOCUMENTO" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" use="required" type="{}IdentificadorDocumento" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UNIDAD" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CodigoDeterminacion">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="REGULACION" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DETERMINACIONES-REGULADORAS" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DETERMINACION-REGULADORA" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="REGULACIONES-ESPECIFICAS" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="REGULACION-ESPECIFICA" type="{}RegulacionEspecifica" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BASE" type="{}CodigoDeterminacion" minOccurs="0"/>
 *         &lt;element name="GRUPOS-APLICACION" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GRUPO-APLICACION" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="codigo" use="required" type="{}IdentificadorDeterminacion" />
 *       &lt;attribute name="caracter" use="required" type="{}IdentificadorCaracterDeterminacion" />
 *       &lt;attribute name="apartado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="etiqueta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="suspendida" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Determinacion", propOrder = {
    "texto",
    "valoresreferencia",
    "hijas",
    "documentos",
    "unidad",
    "regulacion",
    "base",
    "gruposaplicacion"
})
public class Determinacion {

    @XmlElement(name = "TEXTO")
    protected String texto;
    @XmlElement(name = "VALORES-REFERENCIA")
    protected Determinacion.VALORESREFERENCIA valoresreferencia;
    @XmlElement(name = "HIJAS")
    protected Determinacion.HIJAS hijas;
    @XmlElement(name = "DOCUMENTOS")
    protected Determinacion.DOCUMENTOS documentos;
    @XmlElement(name = "UNIDAD")
    protected Determinacion.UNIDAD unidad;
    @XmlElement(name = "REGULACION")
    protected Determinacion.REGULACION regulacion;
    @XmlElement(name = "BASE")
    protected CodigoDeterminacion base;
    @XmlElement(name = "GRUPOS-APLICACION")
    protected Determinacion.GRUPOSAPLICACION gruposaplicacion;
    @XmlAttribute(name = "codigo", required = true)
    protected String codigo;
    @XmlAttribute(name = "caracter", required = true)
    protected String caracter;
    @XmlAttribute(name = "apartado", required = true)
    protected String apartado;
    @XmlAttribute(name = "nombre", required = true)
    protected String nombre;
    @XmlAttribute(name = "etiqueta")
    protected String etiqueta;
    @XmlAttribute(name = "suspendida", required = true)
    protected boolean suspendida;

    /**
     * Gets the value of the texto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTO() {
        return texto;
    }

    /**
     * Sets the value of the texto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTO(String value) {
        this.texto = value;
    }

    /**
     * Gets the value of the valoresreferencia property.
     * 
     * @return
     *     possible object is
     *     {@link Determinacion.VALORESREFERENCIA }
     *     
     */
    public Determinacion.VALORESREFERENCIA getVALORESREFERENCIA() {
        return valoresreferencia;
    }

    /**
     * Sets the value of the valoresreferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Determinacion.VALORESREFERENCIA }
     *     
     */
    public void setVALORESREFERENCIA(Determinacion.VALORESREFERENCIA value) {
        this.valoresreferencia = value;
    }

    /**
     * Gets the value of the hijas property.
     * 
     * @return
     *     possible object is
     *     {@link Determinacion.HIJAS }
     *     
     */
    public Determinacion.HIJAS getHIJAS() {
        return hijas;
    }

    /**
     * Sets the value of the hijas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Determinacion.HIJAS }
     *     
     */
    public void setHIJAS(Determinacion.HIJAS value) {
        this.hijas = value;
    }

    /**
     * Gets the value of the documentos property.
     * 
     * @return
     *     possible object is
     *     {@link Determinacion.DOCUMENTOS }
     *     
     */
    public Determinacion.DOCUMENTOS getDOCUMENTOS() {
        return documentos;
    }

    /**
     * Sets the value of the documentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Determinacion.DOCUMENTOS }
     *     
     */
    public void setDOCUMENTOS(Determinacion.DOCUMENTOS value) {
        this.documentos = value;
    }

    /**
     * Gets the value of the unidad property.
     * 
     * @return
     *     possible object is
     *     {@link Determinacion.UNIDAD }
     *     
     */
    public Determinacion.UNIDAD getUNIDAD() {
        return unidad;
    }

    /**
     * Sets the value of the unidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Determinacion.UNIDAD }
     *     
     */
    public void setUNIDAD(Determinacion.UNIDAD value) {
        this.unidad = value;
    }

    /**
     * Gets the value of the regulacion property.
     * 
     * @return
     *     possible object is
     *     {@link Determinacion.REGULACION }
     *     
     */
    public Determinacion.REGULACION getREGULACION() {
        return regulacion;
    }

    /**
     * Sets the value of the regulacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Determinacion.REGULACION }
     *     
     */
    public void setREGULACION(Determinacion.REGULACION value) {
        this.regulacion = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getBASE() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setBASE(CodigoDeterminacion value) {
        this.base = value;
    }

    /**
     * Gets the value of the gruposaplicacion property.
     * 
     * @return
     *     possible object is
     *     {@link Determinacion.GRUPOSAPLICACION }
     *     
     */
    public Determinacion.GRUPOSAPLICACION getGRUPOSAPLICACION() {
        return gruposaplicacion;
    }

    /**
     * Sets the value of the gruposaplicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Determinacion.GRUPOSAPLICACION }
     *     
     */
    public void setGRUPOSAPLICACION(Determinacion.GRUPOSAPLICACION value) {
        this.gruposaplicacion = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the caracter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaracter() {
        return caracter;
    }

    /**
     * Sets the value of the caracter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaracter(String value) {
        this.caracter = value;
    }

    /**
     * Gets the value of the apartado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApartado() {
        return apartado;
    }

    /**
     * Sets the value of the apartado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApartado(String value) {
        this.apartado = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the etiqueta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtiqueta() {
        return etiqueta;
    }

    /**
     * Sets the value of the etiqueta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtiqueta(String value) {
        this.etiqueta = value;
    }

    /**
     * Gets the value of the suspendida property.
     * 
     */
    public boolean isSuspendida() {
        return suspendida;
    }

    /**
     * Sets the value of the suspendida property.
     * 
     */
    public void setSuspendida(boolean value) {
        this.suspendida = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DOCUMENTO" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" use="required" type="{}IdentificadorDocumento" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documento"
    })
    public static class DOCUMENTOS {

        @XmlElement(name = "DOCUMENTO", required = true)
        protected List<Determinacion.DOCUMENTOS.DOCUMENTO> documento;

        /**
         * Gets the value of the documento property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the documento property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDOCUMENTO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Determinacion.DOCUMENTOS.DOCUMENTO }
         * 
         * 
         */
        public List<Determinacion.DOCUMENTOS.DOCUMENTO> getDOCUMENTO() {
            if (documento == null) {
                documento = new ArrayList<Determinacion.DOCUMENTOS.DOCUMENTO>();
            }
            return this.documento;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" use="required" type="{}IdentificadorDocumento" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DOCUMENTO {

            @XmlAttribute(name = "codigo", required = true)
            protected String codigo;

            /**
             * Gets the value of the codigo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GRUPO-APLICACION" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grupoaplicacion"
    })
    public static class GRUPOSAPLICACION {

        @XmlElement(name = "GRUPO-APLICACION", required = true)
        protected List<CodigoDeterminacion> grupoaplicacion;

        /**
         * Gets the value of the grupoaplicacion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the grupoaplicacion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGRUPOAPLICACION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CodigoDeterminacion }
         * 
         * 
         */
        public List<CodigoDeterminacion> getGRUPOAPLICACION() {
            if (grupoaplicacion == null) {
                grupoaplicacion = new ArrayList<CodigoDeterminacion>();
            }
            return this.grupoaplicacion;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DETERMINACION" type="{}Determinacion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "determinacion"
    })
    public static class HIJAS {

        @XmlElement(name = "DETERMINACION", required = true)
        protected List<Determinacion> determinacion;

        /**
         * Gets the value of the determinacion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the determinacion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDETERMINACION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Determinacion }
         * 
         * 
         */
        public List<Determinacion> getDETERMINACION() {
            if (determinacion == null) {
                determinacion = new ArrayList<Determinacion>();
            }
            return this.determinacion;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DETERMINACIONES-REGULADORAS" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DETERMINACION-REGULADORA" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="REGULACIONES-ESPECIFICAS" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="REGULACION-ESPECIFICA" type="{}RegulacionEspecifica" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "determinacionesreguladoras",
        "regulacionesespecificas"
    })
    public static class REGULACION {

        @XmlElement(name = "DETERMINACIONES-REGULADORAS")
        protected Determinacion.REGULACION.DETERMINACIONESREGULADORAS determinacionesreguladoras;
        @XmlElement(name = "REGULACIONES-ESPECIFICAS")
        protected Determinacion.REGULACION.REGULACIONESESPECIFICAS regulacionesespecificas;

        /**
         * Gets the value of the determinacionesreguladoras property.
         * 
         * @return
         *     possible object is
         *     {@link Determinacion.REGULACION.DETERMINACIONESREGULADORAS }
         *     
         */
        public Determinacion.REGULACION.DETERMINACIONESREGULADORAS getDETERMINACIONESREGULADORAS() {
            return determinacionesreguladoras;
        }

        /**
         * Sets the value of the determinacionesreguladoras property.
         * 
         * @param value
         *     allowed object is
         *     {@link Determinacion.REGULACION.DETERMINACIONESREGULADORAS }
         *     
         */
        public void setDETERMINACIONESREGULADORAS(Determinacion.REGULACION.DETERMINACIONESREGULADORAS value) {
            this.determinacionesreguladoras = value;
        }

        /**
         * Gets the value of the regulacionesespecificas property.
         * 
         * @return
         *     possible object is
         *     {@link Determinacion.REGULACION.REGULACIONESESPECIFICAS }
         *     
         */
        public Determinacion.REGULACION.REGULACIONESESPECIFICAS getREGULACIONESESPECIFICAS() {
            return regulacionesespecificas;
        }

        /**
         * Sets the value of the regulacionesespecificas property.
         * 
         * @param value
         *     allowed object is
         *     {@link Determinacion.REGULACION.REGULACIONESESPECIFICAS }
         *     
         */
        public void setREGULACIONESESPECIFICAS(Determinacion.REGULACION.REGULACIONESESPECIFICAS value) {
            this.regulacionesespecificas = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DETERMINACION-REGULADORA" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "determinacionreguladora"
        })
        public static class DETERMINACIONESREGULADORAS {

            @XmlElement(name = "DETERMINACION-REGULADORA", required = true)
            protected List<CodigoDeterminacion> determinacionreguladora;

            /**
             * Gets the value of the determinacionreguladora property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the determinacionreguladora property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDETERMINACIONREGULADORA().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CodigoDeterminacion }
             * 
             * 
             */
            public List<CodigoDeterminacion> getDETERMINACIONREGULADORA() {
                if (determinacionreguladora == null) {
                    determinacionreguladora = new ArrayList<CodigoDeterminacion>();
                }
                return this.determinacionreguladora;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="REGULACION-ESPECIFICA" type="{}RegulacionEspecifica" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "regulacionespecifica"
        })
        public static class REGULACIONESESPECIFICAS {

            @XmlElement(name = "REGULACION-ESPECIFICA", required = true)
            protected List<RegulacionEspecifica> regulacionespecifica;

            /**
             * Gets the value of the regulacionespecifica property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the regulacionespecifica property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getREGULACIONESPECIFICA().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RegulacionEspecifica }
             * 
             * 
             */
            public List<RegulacionEspecifica> getREGULACIONESPECIFICA() {
                if (regulacionespecifica == null) {
                    regulacionespecifica = new ArrayList<RegulacionEspecifica>();
                }
                return this.regulacionespecifica;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CodigoDeterminacion">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UNIDAD
        extends CodigoDeterminacion
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VALOR-REFERENCIA" type="{}CodigoDeterminacion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valorreferencia"
    })
    public static class VALORESREFERENCIA {

        @XmlElement(name = "VALOR-REFERENCIA", required = true)
        protected List<CodigoDeterminacion> valorreferencia;

        /**
         * Gets the value of the valorreferencia property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the valorreferencia property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVALORREFERENCIA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CodigoDeterminacion }
         * 
         * 
         */
        public List<CodigoDeterminacion> getVALORREFERENCIA() {
            if (valorreferencia == null) {
                valorreferencia = new ArrayList<CodigoDeterminacion>();
            }
            return this.valorreferencia;
        }

    }

}
