/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA


import es.mitc.redes.urbanismoenred.utils.consola.OgridColumnModel;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Ambito generated by hbm2java
 */
public class Ambito  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = -543853182352190264L;
	private int iden;
    private Literal literal;
    private Tipoambito tipoambito;
    private String codigoine;
    private Set<Organigramaambito> organigramaambitosForIdambitopadre = new HashSet<Organigramaambito>(0);
    private Set<Organo> organos = new HashSet<Organo>(0);
    private Set<Organigramaambito> organigramaambitosForIdambitohijo = new HashSet<Organigramaambito>(0);
    private Set<Ambitoshp> ambitoshp = new HashSet<Ambitoshp>(0);

    public Ambito() {
    }

	
    public Ambito(int iden, Tipoambito tipoambito) {
        this.iden = iden;
        this.tipoambito = tipoambito;
    }
    public Ambito(int iden, Literal literal, Tipoambito tipoambito, String codigoine, Set<Organigramaambito> organigramaambitosForIdambitopadre, Set<Organo> organos, Set<Organigramaambito> organigramaambitosForIdambitohijo) {
       this.iden = iden;
       this.literal = literal;
       this.tipoambito = tipoambito;
       this.codigoine = codigoine;
       this.organigramaambitosForIdambitopadre = organigramaambitosForIdambitopadre;
       this.organos = organos;
       this.organigramaambitosForIdambitohijo = organigramaambitosForIdambitohijo;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Literal getLiteral() {
        return this.literal;
    }
    
    public void setLiteral(Literal literal) {
        this.literal = literal;
    }
    public Tipoambito getTipoambito() {
        return this.tipoambito;
    }
    
    public void setTipoambito(Tipoambito tipoambito) {
        this.tipoambito = tipoambito;
    }
    public String getCodigoine() {
        return this.codigoine;
    }
    
    public void setCodigoine(String codigoine) {
        this.codigoine = codigoine;
    }
    public Set<Organigramaambito> getOrganigramaambitosForIdambitopadre() {
        return this.organigramaambitosForIdambitopadre;
    }
    
    public void setOrganigramaambitosForIdambitopadre(Set<Organigramaambito> organigramaambitosForIdambitopadre) {
        this.organigramaambitosForIdambitopadre = organigramaambitosForIdambitopadre;
    }
    public Set<Organo> getOrganos() {
        return this.organos;
    }
    
    public void setOrganos(Set<Organo> organos) {
        this.organos = organos;
    }
    public Set<Organigramaambito> getOrganigramaambitosForIdambitohijo() {
        return this.organigramaambitosForIdambitohijo;
    }
    
    public void setOrganigramaambitosForIdambitohijo(Set<Organigramaambito> organigramaambitosForIdambitohijo) {
        this.organigramaambitosForIdambitohijo = organigramaambitosForIdambitohijo;
    }

    public Set<Ambitoshp> getAmbitoshp() {
        return this.ambitoshp;
    }

    public void setAmbitoshp(Set<Ambitoshp> ambitoshp) {
        this.ambitoshp = ambitoshp;
    }

    public static List<Map<String, Object>> getColumnmodel(){
        List<Map<String, Object>> res = new ArrayList<Map<String, Object>>();
        res.add((new OgridColumnModel("Id", "iden", "number", 50)).toJSON());
        res.add((new OgridColumnModel("Ámbito", "nombre", "string", 200)).toJSON());
        res.add((new OgridColumnModel("Tipo", "tipoambito", "string", 200)).toJSON());
        
        return res;
    }


}


