package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 26-abr-2012 14:16:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrazaId generated by hbm2java
 */
@Embeddable
public class TrazaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1529226189661558291L;
	private int idproceso;
	private String tabla;
	private int idplaneamiento;

	public TrazaId() {
	}

	public TrazaId(int idproceso, String tabla, int idplaneamiento) {
		this.idproceso = idproceso;
		this.tabla = tabla;
		this.idplaneamiento = idplaneamiento;
	}

	@Column(name = "idproceso", nullable = false)
	public int getIdproceso() {
		return this.idproceso;
	}

	public void setIdproceso(int idproceso) {
		this.idproceso = idproceso;
	}

	@Column(name = "tabla", nullable = false, length = 256)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "idplaneamiento", nullable = false)
	public int getIdplaneamiento() {
		return this.idplaneamiento;
	}

	public void setIdplaneamiento(int idplaneamiento) {
		this.idplaneamiento = idplaneamiento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrazaId))
			return false;
		TrazaId castOther = (TrazaId) other;

		return (this.getIdproceso() == castOther.getIdproceso())
				&& ((this.getTabla() == castOther.getTabla()) || (this
						.getTabla() != null && castOther.getTabla() != null && this
						.getTabla().equals(castOther.getTabla())))
				&& (this.getIdplaneamiento() == castOther.getIdplaneamiento());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproceso();
		result = 37 * result
				+ (getTabla() == null ? 0 : this.getTabla().hashCode());
		result = 37 * result + this.getIdplaneamiento();
		return result;
	}

}
