/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Entidaddeterminacionregimen generated by hbm2java
 */
public class Entidaddeterminacionregimen  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2941707315883135094L;
	private int iden;
     private Opciondeterminacion opciondeterminacion;
     private Casoentidaddeterminacion casoentidaddeterminacionByIdcasoaplicacion;
     private Casoentidaddeterminacion casoentidaddeterminacionByIdcaso;
     private Determinacion determinacion;
     private String valor;
     private Integer superposicion;
     private Set<Regimenespecifico> regimenespecificos = new HashSet<Regimenespecifico>(0);

    public Entidaddeterminacionregimen() {
    }

	
    public Entidaddeterminacionregimen(int iden, Casoentidaddeterminacion casoentidaddeterminacionByIdcaso) {
        this.iden = iden;
        this.casoentidaddeterminacionByIdcaso = casoentidaddeterminacionByIdcaso;
    }
    public Entidaddeterminacionregimen(int iden, Opciondeterminacion opciondeterminacion, Casoentidaddeterminacion casoentidaddeterminacionByIdcasoaplicacion, Casoentidaddeterminacion casoentidaddeterminacionByIdcaso, Determinacion determinacion, String valor, Integer superposicion, Set<Regimenespecifico> regimenespecificos) {
       this.iden = iden;
       this.opciondeterminacion = opciondeterminacion;
       this.casoentidaddeterminacionByIdcasoaplicacion = casoentidaddeterminacionByIdcasoaplicacion;
       this.casoentidaddeterminacionByIdcaso = casoentidaddeterminacionByIdcaso;
       this.determinacion = determinacion;
       this.valor = valor;
       this.superposicion = superposicion;
       this.regimenespecificos = regimenespecificos;
    }

      public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Opciondeterminacion getOpciondeterminacion() {
        if (opciondeterminacion!=null){
            opciondeterminacion.getIden();
        }
        return this.opciondeterminacion;
    }
    
    public void setOpciondeterminacion(Opciondeterminacion opciondeterminacion) {
        this.opciondeterminacion = opciondeterminacion;
    }
    public Casoentidaddeterminacion getCasoentidaddeterminacionByIdcasoaplicacion() {
        return this.casoentidaddeterminacionByIdcasoaplicacion;
    }
    
    public void setCasoentidaddeterminacionByIdcasoaplicacion(Casoentidaddeterminacion casoentidaddeterminacionByIdcasoaplicacion) {
        this.casoentidaddeterminacionByIdcasoaplicacion = casoentidaddeterminacionByIdcasoaplicacion;
    }
    public Casoentidaddeterminacion getCasoentidaddeterminacionByIdcaso() {
        return this.casoentidaddeterminacionByIdcaso;
    }
    
    public void setCasoentidaddeterminacionByIdcaso(Casoentidaddeterminacion casoentidaddeterminacionByIdcaso) {
        this.casoentidaddeterminacionByIdcaso = casoentidaddeterminacionByIdcaso;
    }
    public Determinacion getDeterminacion() {
        return this.determinacion;
    }
    
    public void setDeterminacion(Determinacion determinacion) {
        this.determinacion = determinacion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Integer getSuperposicion() {
        return this.superposicion;
    }
    
    public void setSuperposicion(Integer superposicion) {
        this.superposicion = superposicion;
    }
    public Set<Regimenespecifico> getRegimenespecificos() {
        return this.regimenespecificos;
    }
    
    public void setRegimenespecificos(Set<Regimenespecifico> regimenespecificos) {
        this.regimenespecificos = regimenespecificos;
    }




}


