/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA

/**
 * Ambitoshp generated by hbm2java
 */
public class Ambitoshp  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4338477322994981223L;
	private int iden;
     private Integer idambito;
     private String geom;

    public Ambitoshp() {
    }
    
    public Ambitoshp(int iden, int objectid, Integer idambito, Integer shape, String geom) {
       this.iden = iden;
       this.idambito = idambito;
       this.geom = geom;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    
    public Integer getIdambito() {
        return this.idambito;
    }
    
    public void setIdambito(Integer idambito) {
        this.idambito = idambito;
    }
    
    public String getGeom() {
        return this.geom;
    }
    
    public void setGeom(String geom) {
        this.geom = geom;
    }




}


