/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Literal generated by hbm2java
 */
public class Literal  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6662163296584359913L;
	private int iden;
     private String comentario;
     private Set<Tipooperacionplan> tipooperacionplans = new HashSet<Tipooperacionplan>(0);
     private Set<Caracterdeterminacion> caracterdeterminacions = new HashSet<Caracterdeterminacion>(0);
     private Set<Instrumentoplan> instrumentoplans = new HashSet<Instrumentoplan>(0);
     private Set<Tipooperaciondeterminacion> tipooperaciondeterminacions = new HashSet<Tipooperaciondeterminacion>(0);
     private Set<Organo> organos = new HashSet<Organo>(0);
     private Set<Tipoentidad> tipoentidads = new HashSet<Tipoentidad>(0);
     private Set<Tipodocumento> tipodocumentos = new HashSet<Tipodocumento>(0);
     private Set<Sentido> sentidos = new HashSet<Sentido>(0);
     private Set<Traduccion> traduccions = new HashSet<Traduccion>(0);
     private Set<Naturaleza> naturalezas = new HashSet<Naturaleza>(0);
     private Set<Boletin> boletins = new HashSet<Boletin>(0);
     private Set<Defpropiedad> defpropiedads = new HashSet<Defpropiedad>(0);
     private Set<Tipotramite> tipotramites = new HashSet<Tipotramite>(0);
     private Set<Tipooperacionrelacion> tipooperacionrelacions = new HashSet<Tipooperacionrelacion>(0);
     private Set<Centroproduccion> centroproduccions = new HashSet<Centroproduccion>(0);
     private Set<Tipodefpropiedad> tipodefpropiedads = new HashSet<Tipodefpropiedad>(0);
     private Set<Tipooperacionentidad> tipooperacionentidads = new HashSet<Tipooperacionentidad>(0);
     private Set<Tipoambito> tipoambitos = new HashSet<Tipoambito>(0);
     private Set<Defrelacion> defrelacions = new HashSet<Defrelacion>(0);
     private Set<Defvector> defvectors = new HashSet<Defvector>(0);
     private Set<Ambito> ambitos = new HashSet<Ambito>(0);
     private Set<Grupodocumento> grupodocumentos = new HashSet<Grupodocumento>(0);

    public Literal() {
    }


    public Literal(int iden) {
        this.iden = iden;
    }
    public Literal(int iden, String comentario, Set<Tipooperacionplan> tipooperacionplans, Set<Caracterdeterminacion> caracterdeterminacions, Set<Instrumentoplan> instrumentoplans, Set<Tipooperaciondeterminacion> tipooperaciondeterminacions, Set<Organo> organos, Set<Tipoentidad> tipoentidads, Set<Tipodocumento> tipodocumentos, Set<Sentido> sentidos, Set<Traduccion> traduccions, Set<Naturaleza> naturalezas, Set<Boletin> boletins, Set<Defpropiedad> defpropiedads, Set<Tipotramite> tipotramites, Set<Tipooperacionrelacion> tipooperacionrelacions, Set<Centroproduccion> centroproduccions, Set<Tipodefpropiedad> tipodefpropiedads, Set<Tipooperacionentidad> tipooperacionentidads, Set<Tipoambito> tipoambitos, Set<Defrelacion> defrelacions, Set<Defvector> defvectors, Set<Ambito> ambitos, Set<Grupodocumento> grupodocumentos) {
       this.iden = iden;
       this.comentario = comentario;
       this.tipooperacionplans = tipooperacionplans;
       this.caracterdeterminacions = caracterdeterminacions;
       this.instrumentoplans = instrumentoplans;
       this.tipooperaciondeterminacions = tipooperaciondeterminacions;
       this.organos = organos;
       this.tipoentidads = tipoentidads;
       this.tipodocumentos = tipodocumentos;
       this.sentidos = sentidos;
       this.traduccions = traduccions;
       this.naturalezas = naturalezas;
       this.boletins = boletins;
       this.defpropiedads = defpropiedads;
       this.tipotramites = tipotramites;
       this.tipooperacionrelacions = tipooperacionrelacions;
       this.centroproduccions = centroproduccions;
       this.tipodefpropiedads = tipodefpropiedads;
       this.tipooperacionentidads = tipooperacionentidads;
       this.tipoambitos = tipoambitos;
       this.defrelacions = defrelacions;
       this.defvectors = defvectors;
       this.ambitos = ambitos;
       this.grupodocumentos = grupodocumentos;
    }

    public String getTexto(String Idioma){
        Traduccion aTrans=null;
        if (traduccions!=null){
            for(Traduccion aTransTemp: traduccions){
                if (aTransTemp.getIdioma().equalsIgnoreCase(Idioma)){
                    aTrans=aTransTemp;
                    break;
                }
            }
        }

        if (aTrans!=null){
            return aTrans.getTexto();
        }
        else
        {
            if (traduccions.size()>0){
                return ((Traduccion)traduccions.toArray()[0]).getTexto();
            }else{
                return "";
            }
        }
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }
    public String getComentario() {
        return this.comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Set<Tipooperacionplan> getTipooperacionplans() {
        return this.tipooperacionplans;
    }

    public void setTipooperacionplans(Set<Tipooperacionplan> tipooperacionplans) {
        this.tipooperacionplans = tipooperacionplans;
    }
    public Set<Caracterdeterminacion> getCaracterdeterminacions() {
        return this.caracterdeterminacions;
    }

    public void setCaracterdeterminacions(Set<Caracterdeterminacion> caracterdeterminacions) {
        this.caracterdeterminacions = caracterdeterminacions;
    }
    public Set<Instrumentoplan> getInstrumentoplans() {
        return this.instrumentoplans;
    }

    public void setInstrumentoplans(Set<Instrumentoplan> instrumentoplans) {
        this.instrumentoplans = instrumentoplans;
    }
    public Set<Tipooperaciondeterminacion> getTipooperaciondeterminacions() {
        return this.tipooperaciondeterminacions;
    }

    public void setTipooperaciondeterminacions(Set<Tipooperaciondeterminacion> tipooperaciondeterminacions) {
        this.tipooperaciondeterminacions = tipooperaciondeterminacions;
    }
    public Set<Organo> getOrganos() {
        return this.organos;
    }

    public void setOrganos(Set<Organo> organos) {
        this.organos = organos;
    }
    public Set<Tipoentidad> getTipoentidads() {
        return this.tipoentidads;
    }

    public void setTipoentidads(Set<Tipoentidad> tipoentidads) {
        this.tipoentidads = tipoentidads;
    }
    public Set<Tipodocumento> getTipodocumentos() {
        return this.tipodocumentos;
    }

    public void setTipodocumentos(Set<Tipodocumento> tipodocumentos) {
        this.tipodocumentos = tipodocumentos;
    }
    public Set<Sentido> getSentidos() {
        return this.sentidos;
    }

    public void setSentidos(Set<Sentido> sentidos) {
        this.sentidos = sentidos;
    }
    public Set<Traduccion> getTraduccions() {
        return this.traduccions;
    }

    public void setTraduccions(Set<Traduccion> traduccions) {
        this.traduccions = traduccions;
    }
    public Set<Naturaleza> getNaturalezas() {
        return this.naturalezas;
    }

    public void setNaturalezas(Set<Naturaleza> naturalezas) {
        this.naturalezas = naturalezas;
    }
    public Set<Boletin> getBoletins() {
        return this.boletins;
    }

    public void setBoletins(Set<Boletin> boletins) {
        this.boletins = boletins;
    }
    public Set<Defpropiedad> getDefpropiedads() {
        return this.defpropiedads;
    }

    public void setDefpropiedads(Set<Defpropiedad> defpropiedads) {
        this.defpropiedads = defpropiedads;
    }
    public Set<Tipotramite> getTipotramites() {
        return this.tipotramites;
    }

    public void setTipotramites(Set<Tipotramite> tipotramites) {
        this.tipotramites = tipotramites;
    }
    public Set<Tipooperacionrelacion> getTipooperacionrelacions() {
        return this.tipooperacionrelacions;
    }

    public void setTipooperacionrelacions(Set<Tipooperacionrelacion> tipooperacionrelacions) {
        this.tipooperacionrelacions = tipooperacionrelacions;
    }
    public Set<Centroproduccion> getCentroproduccions() {
        return this.centroproduccions;
    }

    public void setCentroproduccions(Set<Centroproduccion> centroproduccions) {
        this.centroproduccions = centroproduccions;
    }
    public Set<Tipodefpropiedad> getTipodefpropiedads() {
        return this.tipodefpropiedads;
    }

    public void setTipodefpropiedads(Set<Tipodefpropiedad> tipodefpropiedads) {
        this.tipodefpropiedads = tipodefpropiedads;
    }
    public Set<Tipooperacionentidad> getTipooperacionentidads() {
        return this.tipooperacionentidads;
    }

    public void setTipooperacionentidads(Set<Tipooperacionentidad> tipooperacionentidads) {
        this.tipooperacionentidads = tipooperacionentidads;
    }
    public Set<Tipoambito> getTipoambitos() {
        return this.tipoambitos;
    }

    public void setTipoambitos(Set<Tipoambito> tipoambitos) {
        this.tipoambitos = tipoambitos;
    }
    public Set<Defrelacion> getDefrelacions() {
        return this.defrelacions;
    }

    public void setDefrelacions(Set<Defrelacion> defrelacions) {
        this.defrelacions = defrelacions;
    }
    public Set<Defvector> getDefvectors() {
        return this.defvectors;
    }

    public void setDefvectors(Set<Defvector> defvectors) {
        this.defvectors = defvectors;
    }
    public Set<Ambito> getAmbitos() {
        return this.ambitos;
    }

    public void setAmbitos(Set<Ambito> ambitos) {
        this.ambitos = ambitos;
    }
    public Set<Grupodocumento> getGrupodocumentos() {
        return this.grupodocumentos;
    }

    public void setGrupodocumentos(Set<Grupodocumento> grupodocumentos) {
        this.grupodocumentos = grupodocumentos;
    }

    public void addTraduccion(String texto, String idioma){
        Traduccion trad = null;
        if (this.traduccions == null){
            this.traduccions = new HashSet<Traduccion>();
            trad = new Traduccion();
            this.traduccions.add(trad);

        } else {
            for (Traduccion t: this.traduccions){
                if (t.getIdioma().equalsIgnoreCase(idioma)){
                    trad = t;
                }
            }
        }

        if (trad == null){
            trad = new Traduccion();
            this.traduccions.add(trad);
        }

        trad.setIdioma(idioma);
        trad.setTexto(texto);
        trad.setLiteral(this);
        
    }




}



