/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA

/**
 * Operacioncaracter generated by hbm2java
 */
public class Operacioncaracter implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -3658898935467644254L;
	private int iden;
    private Tipooperaciondeterminacion tipooperaciondeterminacion;
    private Caracterdeterminacion caracterdeterminacionByIdcaracteroperado;
    private Caracterdeterminacion caracterdeterminacionByIdcaracteroperador;

    public Operacioncaracter() {
    }

    public Operacioncaracter(int iden, Caracterdeterminacion caracterdeterminacionByIdcaracteroperado, Caracterdeterminacion caracterdeterminacionByIdcaracteroperador) {
        this.iden = iden;
        this.caracterdeterminacionByIdcaracteroperado = caracterdeterminacionByIdcaracteroperado;
        this.caracterdeterminacionByIdcaracteroperador = caracterdeterminacionByIdcaracteroperador;
    }

    public Operacioncaracter(int iden, Tipooperaciondeterminacion tipooperaciondeterminacion, Caracterdeterminacion caracterdeterminacionByIdcaracteroperado, Caracterdeterminacion caracterdeterminacionByIdcaracteroperador) {
        this.iden = iden;
        this.tipooperaciondeterminacion = tipooperaciondeterminacion;
        this.caracterdeterminacionByIdcaracteroperado = caracterdeterminacionByIdcaracteroperado;
        this.caracterdeterminacionByIdcaracteroperador = caracterdeterminacionByIdcaracteroperador;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public Tipooperaciondeterminacion getTipooperaciondeterminacion() {
        return this.tipooperaciondeterminacion;
    }

    public void setTipooperaciondeterminacion(Tipooperaciondeterminacion tipooperaciondeterminacion) {
        this.tipooperaciondeterminacion = tipooperaciondeterminacion;
    }

    public Caracterdeterminacion getCaracterdeterminacionByIdcaracteroperado() {
        return this.caracterdeterminacionByIdcaracteroperado;
    }

    public void setCaracterdeterminacionByIdcaracteroperado(Caracterdeterminacion caracterdeterminacionByIdcaracteroperado) {
        this.caracterdeterminacionByIdcaracteroperado = caracterdeterminacionByIdcaracteroperado;
    }

    public Caracterdeterminacion getCaracterdeterminacionByIdcaracteroperador() {
        return this.caracterdeterminacionByIdcaracteroperador;
    }

    public void setCaracterdeterminacionByIdcaracteroperador(Caracterdeterminacion caracterdeterminacionByIdcaracteroperador) {
        this.caracterdeterminacionByIdcaracteroperador = caracterdeterminacionByIdcaracteroperador;
    }
}


