/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA



/**
 * Simbologia generated by hbm2java
 */
public class Simbologia  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -9010091228443213696L;
	private int iden;
     private String descripcion;
     private String sld;

    public Simbologia() {
    }

	
    public Simbologia(int iden, String descripcion) {
        this.iden = iden;
        this.descripcion = descripcion;
    }
    public Simbologia(int iden, String descripcion, String sld) {
       this.iden = iden;
       this.descripcion = descripcion;
       this.sld = sld;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getSld() {
        return this.sld;
    }
    
    public void setSld(String sld) {
        this.sld = sld;
    }




}


