/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tabla generated by hbm2java
 */
public class Tabla  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5032329754650163725L;
	private int iden;
     private String nombre;
     private String clausulawhere;
     private String observaciones;
     private String esquema;
     private Set<Defvector> defvectors = new HashSet<Defvector>(0);

    public Tabla() {
    }

	
    public Tabla(int iden, String nombre, String clausulawhere, String observaciones) {
        this.iden = iden;
        this.nombre = nombre;
        this.clausulawhere = clausulawhere;
        this.observaciones = observaciones;
    }
    public Tabla(int iden, String nombre, String clausulawhere, String observaciones, String esquema, Set<Defvector> defvectors) {
       this.iden = iden;
       this.nombre = nombre;
       this.clausulawhere = clausulawhere;
       this.observaciones = observaciones;
       this.esquema = esquema;
       this.defvectors = defvectors;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClausulawhere() {
        return this.clausulawhere;
    }
    
    public void setClausulawhere(String clausulawhere) {
        this.clausulawhere = clausulawhere;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEsquema() {
        return this.esquema;
    }
    
    public void setEsquema(String esquema) {
        this.esquema = esquema;
    }
    public Set<Defvector> getDefvectors() {
        return this.defvectors;
    }
    
    public void setDefvectors(Set<Defvector> defvectors) {
        this.defvectors = defvectors;
    }




}


