/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoambito generated by hbm2java
 */
public class Tipoambito  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -9167529583098052793L;
	private int iden;
     private Literal literal;
     private Integer idpadre;
     private Set<Ambito> ambitos = new HashSet<Ambito>(0);

    public Tipoambito() {
    }

	
    public Tipoambito(int iden) {
        this.iden = iden;
    }
    public Tipoambito(int iden, Literal literal, Integer idpadre, Set<Ambito> ambitos) {
       this.iden = iden;
       this.literal = literal;
       this.idpadre = idpadre;
       this.ambitos = ambitos;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Literal getLiteral() {
        return this.literal;
    }
    
    public void setLiteral(Literal literal) {
        this.literal = literal;
    }
    public Integer getIdpadre() {
        return this.idpadre;
    }
    
    public void setIdpadre(Integer idpadre) {
        this.idpadre = idpadre;
    }
    public Set<Ambito> getAmbitos() {
        return this.ambitos;
    }
    
    public void setAmbitos(Set<Ambito> ambitos) {
        this.ambitos = ambitos;
    }




}


