/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoentidad generated by hbm2java
 */
public class Tipoentidad  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1618111253132162971L;
	private int iden;
     private Literal literal;
     private Set<Tipooperacionentidad> tipooperacionentidads = new HashSet<Tipooperacionentidad>(0);

    public Tipoentidad() {
    }

	
    public Tipoentidad(int iden, Literal literal) {
        this.iden = iden;
        this.literal = literal;
    }
    public Tipoentidad(int iden, Literal literal, Set<Tipooperacionentidad> tipooperacionentidads) {
       this.iden = iden;
       this.literal = literal;
       this.tipooperacionentidads = tipooperacionentidads;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Literal getLiteral() {
        return this.literal;
    }
    
    public void setLiteral(Literal literal) {
        this.literal = literal;
    }
    public Set<Tipooperacionentidad> getTipooperacionentidads() {
        return this.tipooperacionentidads;
    }
    
    public void setTipooperacionentidads(Set<Tipooperacionentidad> tipooperacionentidads) {
        this.tipooperacionentidads = tipooperacionentidads;
    }




}


