/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

/**
 * Operaciondeterminacion generated by hbm2java
 */
public class Operaciondeterminacion implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8927615514668444916L;
	private int iden;
    private Operacion operacion;
    private Determinacion determinacionByIddeterminacion;
    private Determinacion determinacionByIddeterminacionoperadora;
    private int idtipooperaciondet;

    public Operaciondeterminacion() {
    }

    public Operaciondeterminacion(int iden, Operacion operacion, Determinacion determinacionByIddeterminacion, Determinacion determinacionByIddeterminacionoperadora, int idtipooperaciondet) {
        this.iden = iden;
        this.operacion = operacion;
        this.determinacionByIddeterminacion = determinacionByIddeterminacion;
        this.determinacionByIddeterminacionoperadora = determinacionByIddeterminacionoperadora;
        this.idtipooperaciondet = idtipooperaciondet;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public Operacion getOperacion() {
        return this.operacion;
    }

    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }

    public Determinacion getDeterminacionByIddeterminacion() {
        return this.determinacionByIddeterminacion;
    }

    public void setDeterminacionByIddeterminacion(Determinacion determinacionByIddeterminacion) {
        this.determinacionByIddeterminacion = determinacionByIddeterminacion;
    }

    public Determinacion getDeterminacionByIddeterminacionoperadora() {
        return this.determinacionByIddeterminacionoperadora;
    }

    public void setDeterminacionByIddeterminacionoperadora(Determinacion determinacionByIddeterminacionoperadora) {
        this.determinacionByIddeterminacionoperadora = determinacionByIddeterminacionoperadora;
    }

    public int getIdtipooperaciondet() {
        return this.idtipooperaciondet;
    }

    public void setIdtipooperaciondet(int idtipooperaciondet) {
        this.idtipooperaciondet = idtipooperaciondet;
    }
}


