/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.seguridad;
// Generated 18-ene-2010 19:40:37 by Hibernate Tools 3.2.1.GA

import java.util.HashMap;
import java.util.Map;




/**
 * Subsistema generated by hbm2java
 */
public class Subsistema  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1798366358731173505L;
	private int iden;
     private String nombre;

    public Subsistema() {
    }

	
    public Subsistema(int iden) {
        this.iden = iden;
    }
    public Subsistema(int iden, String nombre) {
       this.iden = iden;
       this.nombre = nombre;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Map<String, Object> toJSON(){
        Map<String, Object> res = new HashMap<String, Object>();
        res.put("iden", this.getIden());
        res.put("nombre", this.getNombre());
        return res;
    }


}


