/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Relacion generated by hbm2java
 */
public class Relacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6820072904695145384L;
	private int iden;
     private Tramite tramiteByIdtramitecreador;
     private int iddefrelacion;
     private Set<Operacionrelacion> operacionrelacions = new HashSet<Operacionrelacion>(0);
     private Set<Propiedadrelacion> propiedadrelacions = new HashSet<Propiedadrelacion>(0);
     private Set<Vectorrelacion> vectorrelacions = new HashSet<Vectorrelacion>(0);

    public Relacion() {
    }

	
    public Relacion(int iden, Tramite tramiteByIdtramitecreador, int iddefrelacion) {
        this.iden = iden;
        this.tramiteByIdtramitecreador = tramiteByIdtramitecreador;
        this.iddefrelacion = iddefrelacion;
    }
    public Relacion(int iden, Tramite tramiteByIdtramitecreador, int iddefrelacion, Set<Operacionrelacion> operacionrelacions, Set<Propiedadrelacion> propiedadrelacions, Set<Vectorrelacion> vectorrelacions) {
       this.iden = iden;
       this.tramiteByIdtramitecreador = tramiteByIdtramitecreador;
       this.iddefrelacion = iddefrelacion;
       this.operacionrelacions = operacionrelacions;
       this.propiedadrelacions = propiedadrelacions;
       this.vectorrelacions = vectorrelacions;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    
    public Tramite getTramiteByIdtramitecreador() {
        return this.tramiteByIdtramitecreador;
    }
    
    public void setTramiteByIdtramitecreador(Tramite tramiteByIdtramitecreador) {
        this.tramiteByIdtramitecreador = tramiteByIdtramitecreador;
    }
    public int getIddefrelacion() {
        return this.iddefrelacion;
    }
    
    public void setIddefrelacion(int iddefrelacion) {
        this.iddefrelacion = iddefrelacion;
    }
    public Set<Operacionrelacion> getOperacionrelacions() {
        return this.operacionrelacions;
    }
    
    public void setOperacionrelacions(Set<Operacionrelacion> operacionrelacions) {
        this.operacionrelacions = operacionrelacions;
    }
    public Set<Propiedadrelacion> getPropiedadrelacions() {
        return this.propiedadrelacions;
    }
    
    public void setPropiedadrelacions(Set<Propiedadrelacion> propiedadrelacions) {
        this.propiedadrelacions = propiedadrelacions;
    }
    public Set<Vectorrelacion> getVectorrelacions() {
        return this.vectorrelacions;
    }
    
    public void setVectorrelacions(Set<Vectorrelacion> vectorrelacions) {
        this.vectorrelacions = vectorrelacions;
    }




}


