package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operacion generated by hbm2java
 */
@Entity
@Table(name = "operacion")
public class Operacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7934758362904514419L;
	private int iden;
	private Tramite tramite;
	private String texto;
	private int orden;
	private Set<Operacionentidad> operacionentidads = new HashSet<Operacionentidad>(
			0);
	private Set<Operaciondeterminacion> operaciondeterminacions = new HashSet<Operaciondeterminacion>(
			0);
	private Set<Operacionrelacion> operacionrelacions = new HashSet<Operacionrelacion>(
			0);

	public Operacion() {
	}

	public Operacion(int iden, Tramite tramite, int orden) {
		this.iden = iden;
		this.tramite = tramite;
		this.orden = orden;
	}

	public Operacion(int iden, Tramite tramite, String texto, int orden,
			Set<Operacionentidad> operacionentidads,
			Set<Operaciondeterminacion> operaciondeterminacions,
			Set<Operacionrelacion> operacionrelacions) {
		this.iden = iden;
		this.tramite = tramite;
		this.texto = texto;
		this.orden = orden;
		this.operacionentidads = operacionentidads;
		this.operaciondeterminacions = operaciondeterminacions;
		this.operacionrelacions = operacionrelacions;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtramiteordenante", nullable = false)
	public Tramite getTramite() {
		return this.tramite;
	}

	public void setTramite(Tramite tramite) {
		this.tramite = tramite;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operacion")
	public Set<Operacionentidad> getOperacionentidads() {
		return this.operacionentidads;
	}

	public void setOperacionentidads(Set<Operacionentidad> operacionentidads) {
		this.operacionentidads = operacionentidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operacion")
	public Set<Operaciondeterminacion> getOperaciondeterminacions() {
		return this.operaciondeterminacions;
	}

	public void setOperaciondeterminacions(
			Set<Operaciondeterminacion> operaciondeterminacions) {
		this.operaciondeterminacions = operaciondeterminacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operacion")
	public Set<Operacionrelacion> getOperacionrelacions() {
		return this.operacionrelacions;
	}

	public void setOperacionrelacions(Set<Operacionrelacion> operacionrelacions) {
		this.operacionrelacions = operacionrelacions;
	}

}
