/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.seguridad;
// Generated 13-oct-2009 13:54:46 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -3887536539312500784L;
	private int iden;
     private String nombre;
     private String codigo;
     private Set<Usuariorol> usuariorols = new HashSet<Usuariorol>(0);

    public Rol() {
    }

	
    public Rol(int iden, String nombre, String codigo) {
        this.iden = iden;
        this.nombre = nombre;
        this.codigo = codigo;
    }
    public Rol(int iden, String nombre, String codigo, Set<Usuariorol> usuariorols) {
       this.iden = iden;
       this.nombre = nombre;
       this.codigo = codigo;
       this.usuariorols = usuariorols;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set<Usuariorol> getUsuariorols() {
        return this.usuariorols;
    }
    
    public void setUsuariorols(Set<Usuariorol> usuariorols) {
        this.usuariorols = usuariorols;
    }




}


