/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.seguridad;
// Generated 13-oct-2009 13:54:46 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6150568481499392072L;
	private int iden;
    private String nombre;
    private String passwordmd5;
    private String correo;
    private String dni;
    private Set<Usuariorol> usuariorols = new HashSet<Usuariorol>(0);

    public Usuario() {
    }

    public Usuario(int iden, String nombre, String passwordmd5, String correo) {
        this.iden = iden;
        this.nombre = nombre;
        this.passwordmd5 = passwordmd5;
        this.correo = correo;
    }

    public Usuario(int iden, String nombre, String passwordmd5, String correo, Set<Usuariorol> usuariorols) {
        this.iden = iden;
        this.nombre = nombre;
        this.passwordmd5 = passwordmd5;
        this.usuariorols = usuariorols;
        this.correo = correo;
    }

    public Usuario(int iden, String nombre, String passwordmd5, String correo,String dni) {
        this.iden = iden;
        this.nombre = nombre;
        this.passwordmd5 = passwordmd5;
        this.correo = correo;
        this.dni=dni;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPasswordmd5() {
        return this.passwordmd5;
    }

    public void setPasswordmd5(String passwordmd5) {
        this.passwordmd5 = passwordmd5;
    }

    public String getCorreo(){
        return this.correo;
    }

    public void setCorreo(String correo){
        this.correo = correo;
    }

    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }


    public Set<Usuariorol> getUsuariorols() {
        return this.usuariorols;
    }

    public void setUsuariorols(Set<Usuariorol> usuariorols) {
        this.usuariorols = usuariorols;
    }
}


