/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;


/**
 * Entidad generated by hbm2java
 */
public class Entidad implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 72272110398011389L;
	private int iden;
    private Tramite tramite;
    private Entidad entidadByIdentidadoriginal;
    private Entidad entidadByIdentidadbase;
    private Entidad entidadByIdpadre;
    private String nombre;
    private String clave;
    private String etiqueta;
    private String codigo;
    private boolean bsuspendida;
    private int orden;
    private Set<Entidadpnt> entidadpnts = new HashSet<Entidadpnt>(0);
    private Set<Entidaddeterminacion> entidaddeterminacions = new HashSet<Entidaddeterminacion>(0);
    private Set<Documentoentidad> documentoentidads = new HashSet<Documentoentidad>(0);
    private Set<Operacionentidad> operacionentidadsForIdentidad = new HashSet<Operacionentidad>(0);
    private Set<Entidadlin> entidadlins = new HashSet<Entidadlin>(0);
    private Set<Entidad> entidadsForIdpadre = new HashSet<Entidad>(0);
    private Set<Entidad> entidadsForIdentidadoriginal = new HashSet<Entidad>(0);
    private Set<Entidad> entidadsForIdentidadbase = new HashSet<Entidad>(0);
    private Set<Ambitoaplicacionambito> ambitoaplicacionambitos = new HashSet<Ambitoaplicacionambito>(0);
    private Set<Entidadpol> entidadpols = new HashSet<Entidadpol>(0);
    private Set<Operacionentidad> operacionentidadsForIdentidadoperadora = new HashSet<Operacionentidad>(0);
    private Set<Planentidadordenacion> planentidadordenacions = new HashSet<Planentidadordenacion>(0);

    public Entidad() {
    }

    public Entidad(int iden, Tramite tramite, String codigo, boolean bsuspendida, int orden) {
        this.iden = iden;
        this.tramite = tramite;
        this.codigo = codigo;
        this.bsuspendida = bsuspendida;
        this.orden = orden;
    }

    public Entidad(int iden, Tramite tramite, Entidad entidadByIdentidadoriginal, Entidad entidadByIdentidadbase, Entidad entidadByIdpadre, String nombre, String clave, String etiqueta, String codigo, boolean bsuspendida, int orden,  Set<Entidadpnt> entidadpnts, Set<Entidaddeterminacion> entidaddeterminacions, Set<Documentoentidad> documentoentidads, Set<Operacionentidad> operacionentidadsForIdentidad, Set<Entidadlin> entidadlins,  Set<Entidad> entidadsForIdpadre, Set<Entidad> entidadsForIdentidadoriginal, Set<Entidad> entidadsForIdentidadbase, Set<Ambitoaplicacionambito> ambitoaplicacionambitos, Set<Entidadpol> entidadpols, Set<Operacionentidad> operacionentidadsForIdentidadoperadora, Set<Planentidadordenacion> planentidadordenacions) {
        this.iden = iden;
        this.tramite = tramite;
        this.entidadByIdentidadoriginal = entidadByIdentidadoriginal;
        this.entidadByIdentidadbase = entidadByIdentidadbase;
        this.entidadByIdpadre = entidadByIdpadre;
        this.nombre = nombre;
        this.clave = clave;
        this.etiqueta = etiqueta;
        this.codigo = codigo;
        this.bsuspendida = bsuspendida;
        this.orden = orden;
        this.entidadpnts = entidadpnts;
        this.entidaddeterminacions = entidaddeterminacions;
        this.documentoentidads = documentoentidads;
        this.operacionentidadsForIdentidad = operacionentidadsForIdentidad;
        this.entidadlins = entidadlins;
        this.entidadsForIdpadre = entidadsForIdpadre;
        this.entidadsForIdentidadoriginal = entidadsForIdentidadoriginal;
        this.entidadsForIdentidadbase = entidadsForIdentidadbase;
        this.ambitoaplicacionambitos = ambitoaplicacionambitos;
        this.entidadpols = entidadpols;
        this.operacionentidadsForIdentidadoperadora = operacionentidadsForIdentidadoperadora;
        this.planentidadordenacions = planentidadordenacions;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public Tramite getTramite() {
        return this.tramite;
    }

    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }

    public Entidad getEntidadByIdentidadoriginal() {
        return this.entidadByIdentidadoriginal;
    }

    public void setEntidadByIdentidadoriginal(Entidad entidadByIdentidadoriginal) {
        this.entidadByIdentidadoriginal = entidadByIdentidadoriginal;
    }

    public Entidad getEntidadByIdentidadbase() {
        return this.entidadByIdentidadbase;
    }

    public void setEntidadByIdentidadbase(Entidad entidadByIdentidadbase) {
        this.entidadByIdentidadbase = entidadByIdentidadbase;
    }

    public Entidad getEntidadByIdpadre() {
        return this.entidadByIdpadre;
    }

    public void setEntidadByIdpadre(Entidad entidadByIdpadre) {
        this.entidadByIdpadre = entidadByIdpadre;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public String getEtiqueta() {
        return this.etiqueta;
    }

    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public boolean isBsuspendida() {
        return this.bsuspendida;
    }

    public void setBsuspendida(boolean bsuspendida) {
        this.bsuspendida = bsuspendida;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }


    public Set<Entidadpnt> getEntidadpnts() {
        return this.entidadpnts;
    }

    public void setEntidadpnts(Set<Entidadpnt> entidadpnts) {
        this.entidadpnts = entidadpnts;
    }

    public Set<Entidaddeterminacion> getEntidaddeterminacions() {
        return this.entidaddeterminacions;
    }

    public void setEntidaddeterminacions(Set<Entidaddeterminacion> entidaddeterminacions) {
        this.entidaddeterminacions = entidaddeterminacions;
    }

    public Set<Documentoentidad> getDocumentoentidads() {
        return this.documentoentidads;
    }

    public void setDocumentoentidads(Set<Documentoentidad> documentoentidads) {
        this.documentoentidads = documentoentidads;
    }

    public Set<Operacionentidad> getOperacionentidadsForIdentidad() {
        return this.operacionentidadsForIdentidad;
    }

    public void setOperacionentidadsForIdentidad(Set<Operacionentidad> operacionentidadsForIdentidad) {
        this.operacionentidadsForIdentidad = operacionentidadsForIdentidad;
    }

    public Set<Entidadlin> getEntidadlins() {
        return this.entidadlins;
    }

    public void setEntidadlins(Set<Entidadlin> entidadlins) {
        this.entidadlins = entidadlins;
    }



    public Set<Entidad> getEntidadsForIdpadre() {
        return this.entidadsForIdpadre;
    }

    public void setEntidadsForIdpadre(Set<Entidad> entidadsForIdpadre) {
        this.entidadsForIdpadre = entidadsForIdpadre;
    }

    public Set<Entidad> getEntidadsForIdentidadoriginal() {
        return this.entidadsForIdentidadoriginal;
    }

    public void setEntidadsForIdentidadoriginal(Set<Entidad> entidadsForIdentidadoriginal) {
        this.entidadsForIdentidadoriginal = entidadsForIdentidadoriginal;
    }

    public Set<Entidad> getEntidadsForIdentidadbase() {
        return this.entidadsForIdentidadbase;
    }

    public void setEntidadsForIdentidadbase(Set<Entidad> entidadsForIdentidadbase) {
        this.entidadsForIdentidadbase = entidadsForIdentidadbase;
    }

    public Set<Ambitoaplicacionambito> getAmbitoaplicacionambitos() {
        return this.ambitoaplicacionambitos;
    }

    public void setAmbitoaplicacionambitos(Set<Ambitoaplicacionambito> ambitoaplicacionambitos) {
        this.ambitoaplicacionambitos = ambitoaplicacionambitos;
    }

    public Set<Entidadpol> getEntidadpols() {
        return this.entidadpols;
    }

    public void setEntidadpols(Set<Entidadpol> entidadpols) {
        this.entidadpols = entidadpols;
    }

    public Set<Operacionentidad> getOperacionentidadsForIdentidadoperadora() {
        return this.operacionentidadsForIdentidadoperadora;
    }

    public void setOperacionentidadsForIdentidadoperadora(Set<Operacionentidad> operacionentidadsForIdentidadoperadora) {
        this.operacionentidadsForIdentidadoperadora = operacionentidadsForIdentidadoperadora;
    }

    public Set<Planentidadordenacion> getPlanentidadordenacions() {
        return this.planentidadordenacions;
    }

    public void setPlanentidadordenacions(Set<Planentidadordenacion> planentidadordenacions) {
        this.planentidadordenacions = planentidadordenacions;
    }
}


