/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

/**
 * Operacionplan generated by hbm2java
 */
public class Operacionplan  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5818164264864426171L;
	private int iden;
     private Plan planByIdplanoperador;
     private Plan planByIdplanoperado;
     private int idinstrumentotipooperacion;

    public Operacionplan() {
    }

	
    public Operacionplan(int iden, Plan planByIdplanoperador, int idinstrumentotipooperacion) {
        this.iden = iden;
        this.planByIdplanoperador = planByIdplanoperador;
        this.idinstrumentotipooperacion = idinstrumentotipooperacion;
    }
    public Operacionplan(int iden, Plan planByIdplanoperador, Plan planByIdplanoperado, int idinstrumentotipooperacion) {
       this.iden = iden;
       this.planByIdplanoperador = planByIdplanoperador;
       this.planByIdplanoperado = planByIdplanoperado;
       this.idinstrumentotipooperacion = idinstrumentotipooperacion;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Plan getPlanByIdplanoperador() {
        return this.planByIdplanoperador;
    }
    
    public void setPlanByIdplanoperador(Plan planByIdplanoperador) {
        this.planByIdplanoperador = planByIdplanoperador;
    }
    public Plan getPlanByIdplanoperado() {
        return this.planByIdplanoperado;
    }
    
    public void setPlanByIdplanoperado(Plan planByIdplanoperado) {
        this.planByIdplanoperado = planByIdplanoperado;
    }
    public int getIdinstrumentotipooperacion() {
        return this.idinstrumentotipooperacion;
    }
    
    public void setIdinstrumentotipooperacion(int idinstrumentotipooperacion) {
        this.idinstrumentotipooperacion = idinstrumentotipooperacion;
    }
}


