package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vinculocaso generated by hbm2java
 */
@Entity
@Table(name = "vinculocaso")
public class Vinculocaso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3263863779290163936L;
	private int iden;
	private Casoentidaddeterminacion casoentidaddeterminacionByIdcasovinculado;
	private Casoentidaddeterminacion casoentidaddeterminacionByIdcaso;

	public Vinculocaso() {
	}

	public Vinculocaso(int iden,
			Casoentidaddeterminacion casoentidaddeterminacionByIdcasovinculado,
			Casoentidaddeterminacion casoentidaddeterminacionByIdcaso) {
		this.iden = iden;
		this.casoentidaddeterminacionByIdcasovinculado = casoentidaddeterminacionByIdcasovinculado;
		this.casoentidaddeterminacionByIdcaso = casoentidaddeterminacionByIdcaso;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcasovinculado", nullable = false)
	public Casoentidaddeterminacion getCasoentidaddeterminacionByIdcasovinculado() {
		return this.casoentidaddeterminacionByIdcasovinculado;
	}

	public void setCasoentidaddeterminacionByIdcasovinculado(
			Casoentidaddeterminacion casoentidaddeterminacionByIdcasovinculado) {
		this.casoentidaddeterminacionByIdcasovinculado = casoentidaddeterminacionByIdcasovinculado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcaso", nullable = false)
	public Casoentidaddeterminacion getCasoentidaddeterminacionByIdcaso() {
		return this.casoentidaddeterminacionByIdcaso;
	}

	public void setCasoentidaddeterminacionByIdcaso(
			Casoentidaddeterminacion casoentidaddeterminacionByIdcaso) {
		this.casoentidaddeterminacionByIdcaso = casoentidaddeterminacionByIdcaso;
	}

}
