/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.seguridad;
// Generated 22-ene-2010 11:19:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Operaciones generated by hbm2java
 */
public class Operaciones  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4451836094360656606L;
	private int iden;
     private String nombre;
     private Date horainicio;
     private Set<Diario> diarios = new HashSet<Diario>(0);

    public Operaciones() {
    }

	
    public Operaciones(int iden, String nombre) {
        this.iden = iden;
        this.nombre = nombre;
    }
    public Operaciones(int iden, String nombre, Date horainicio, Set<Diario> diarios) {
       this.iden = iden;
       this.nombre = nombre;
       this.horainicio = horainicio;
       this.diarios = diarios;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getHorainicio() {
        return this.horainicio;
    }
    
    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }
    public Set<Diario> getDiarios() {
        return this.diarios;
    }
    
    public void setDiarios(Set<Diario> diarios) {
        this.diarios = diarios;
    }




}


