package es.mitc.redes.urbanismoenred.data.rpm.ficha;

// Generated 21-nov-2011 17:20:25 by Hibernate Tools 3.4.0.CR1

/**
 * Fichaconjuntogrupo generated by hbm2java
 */
public class Fichaconjuntogrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6273239142851573909L;
	private long iden;
	private Conjuntogrupo conjuntogrupo;
	private Ficha ficha;
	private long orden;
        private boolean regimen_directo;
        private boolean usos;
        private boolean actos;
        
	public Fichaconjuntogrupo() {
	}

	public Fichaconjuntogrupo(long iden, Conjuntogrupo conjuntogrupo,
			Ficha ficha, long orden,boolean regimen_directo,boolean usos,boolean actos) {
		this.iden = iden;
		this.conjuntogrupo = conjuntogrupo;
		this.ficha = ficha;
		this.orden = orden;
                this.regimen_directo = regimen_directo;
                this.usos = usos;
                this.actos = actos;
                
	}

	public long getIden() {
		return this.iden;
	}

	public void setIden(long iden) {
		this.iden = iden;
	}

	public Conjuntogrupo getConjuntogrupo() {
		return this.conjuntogrupo;
	}

	public void setConjuntogrupo(Conjuntogrupo conjuntogrupo) {
		this.conjuntogrupo = conjuntogrupo;
	}

	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}

        public boolean isRegimen_directo() {
		return this.regimen_directo;
	}

	public void setRegimen_directo(boolean regimen_directo) {
		this.regimen_directo = regimen_directo;
	}
        
        public boolean isActos() {
		return this.actos;
	}

	public void setActos(boolean actos) {
		this.actos = actos;
	}
        
        public boolean isUsos() {
		return this.usos;
	}

	public void setUsos(boolean usos) {
		this.usos = usos;
	}
}
