/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

/**
 * Operacionentidad generated by hbm2java
 */
public class Operacionentidad implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3271371575805681167L;
	private int iden;
    private Entidad entidadByIdentidadoperadora;
    private Entidad entidadByIdentidad;
    private Operacion operacion;
    private int idtipooperacionent;

    public Operacionentidad() {
    }

    public Operacionentidad(int iden, Entidad entidadByIdentidadoperadora, Entidad entidadByIdentidad, Operacion operacion, int idtipooperacionent) {
        this.iden = iden;
        this.entidadByIdentidadoperadora = entidadByIdentidadoperadora;
        this.entidadByIdentidad = entidadByIdentidad;
        this.operacion = operacion;
        this.idtipooperacionent = idtipooperacionent;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public Entidad getEntidadByIdentidadoperadora() {
        return this.entidadByIdentidadoperadora;
    }

    public void setEntidadByIdentidadoperadora(Entidad entidadByIdentidadoperadora) {
        this.entidadByIdentidadoperadora = entidadByIdentidadoperadora;
    }

    public Entidad getEntidadByIdentidad() {
        return this.entidadByIdentidad;
    }

    public void setEntidadByIdentidad(Entidad entidadByIdentidad) {
        this.entidadByIdentidad = entidadByIdentidad;
    }

    public Operacion getOperacion() {
        return this.operacion;
    }

    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }

    public int getIdtipooperacionent() {
        return this.idtipooperacionent;
    }

    public void setIdtipooperacionent(int idtipooperacionent) {
        this.idtipooperacionent = idtipooperacionent;
    }
}


