/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -8718972997140232336L;
	private int iden;
    private Plan planByIdpadre;
    private Plan planByIdplanbase;
    private String nombre;
    private String codigo;
    private String texto;
    private int idambito;
    private boolean bsuspendido;
    private int orden;
    private Set<Plan> plansForIdplanbase = new HashSet<Plan>(0);
    private Set<Planentidadordenacion> planentidadordenacions = new HashSet<Planentidadordenacion>(0);
    private Set<Operacionplan> operacionplansForIdplanoperador = new HashSet<Operacionplan>(0);
    private Set<Planshp> planshps = new HashSet<Planshp>(0);
    private Set<Tramite> tramites = new HashSet<Tramite>(0);
    private Set<Operacionplan> operacionplansForIdplanoperado = new HashSet<Operacionplan>(0);
    private Set<Plan> plansForIdpadre = new HashSet<Plan>(0);

    public Plan() {
    }

    public Plan(int iden, String nombre, String codigo, int idambito, Boolean bsuspendido, int orden) {
        this.iden = iden;
        this.nombre = nombre;
        this.codigo = codigo;
        this.idambito = idambito;
        this.bsuspendido = bsuspendido;
        this.orden = orden;
    }

    public Plan(int iden, Plan planByIdpadre, Plan planByIdplanbase, String nombre, String codigo, String texto, boolean bsuspendido, int orden, int idambito, Set<Plan> plansForIdplanbase, Set<Planentidadordenacion> planentidadordenacions, Set<Operacionplan> operacionplansForIdplanoperador, Set<Planshp> planshps, Set<Tramite> tramites, Set<Operacionplan> operacionplansForIdplanoperado, Set<Plan> plansForIdpadre) {
        this.iden = iden;
        this.planByIdpadre = planByIdpadre;
        this.planByIdplanbase = planByIdplanbase;
        this.nombre = nombre;
        this.codigo = codigo;
        this.texto = texto;
        this.bsuspendido = bsuspendido;
        this.orden = orden;
        this.idambito = idambito;
        this.plansForIdplanbase = plansForIdplanbase;
        this.planentidadordenacions = planentidadordenacions;
        this.operacionplansForIdplanoperador = operacionplansForIdplanoperador;
        this.planshps = planshps;
        this.tramites = tramites;
        this.operacionplansForIdplanoperado = operacionplansForIdplanoperado;
        this.plansForIdpadre = plansForIdpadre;
    }

    public void setBsuspendido(boolean bsuspendido) {
        this.bsuspendido = bsuspendido;
    }

    public Boolean getBsuspendido() {
        return this.bsuspendido;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public Plan getPlanByIdpadre() {
        return this.planByIdpadre;
    }

    public void setPlanByIdpadre(Plan planByIdpadre) {
        this.planByIdpadre = planByIdpadre;
    }

    public Plan getPlanByIdplanbase() {
        return this.planByIdplanbase;
    }

    public void setPlanByIdplanbase(Plan planByIdplanbase) {
        this.planByIdplanbase = planByIdplanbase;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public int getIdambito() {
        return this.idambito;
    }

    public void setIdambito(int idambito) {
        this.idambito = idambito;
    }

    public Set<Plan> getPlansForIdplanbase() {
        return this.plansForIdplanbase;
    }

    public void setPlansForIdplanbase(Set<Plan> plansForIdplanbase) {
        this.plansForIdplanbase = plansForIdplanbase;
    }

    public Set<Planentidadordenacion> getPlanentidadordenacions() {
        return this.planentidadordenacions;
    }

    public void setPlanentidadordenacions(Set<Planentidadordenacion> planentidadordenacions) {
        this.planentidadordenacions = planentidadordenacions;
    }

    public Set<Operacionplan> getOperacionplansForIdplanoperador() {
        return this.operacionplansForIdplanoperador;
    }

    public void setOperacionplansForIdplanoperador(Set<Operacionplan> operacionplansForIdplanoperador) {
        this.operacionplansForIdplanoperador = operacionplansForIdplanoperador;
    }

    public Set<Planshp> getPlanshps() {
        return this.planshps;
    }

    public void setPlanshps(Set<Planshp> planshps) {
        this.planshps = planshps;
    }

    public Set<Tramite> getTramites() {
        return this.tramites;
    }

    public void setTramites(Set<Tramite> tramites) {
        this.tramites = tramites;
    }

    public Set<Operacionplan> getOperacionplansForIdplanoperado() {
        return this.operacionplansForIdplanoperado;
    }

    public void setOperacionplansForIdplanoperado(Set<Operacionplan> operacionplansForIdplanoperado) {
        this.operacionplansForIdplanoperado = operacionplansForIdplanoperado;
    }

    public Set<Plan> getPlansForIdpadre() {
        return this.plansForIdpadre;
    }

    public void setPlansForIdpadre(Set<Plan> plansForIdpadre) {
        this.plansForIdpadre = plansForIdpadre;
    }
}


