/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.validacion;

// Generated 18-jul-2011 17:35:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proceso generated by hbm2java
 */
@Entity(name="es.mitc.redes.urbanismoenred.data.validacion.Proceso")
@Table(name = "proceso", schema="validacion")
public class Proceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5661305547988201602L;
	private int iden;
	private String idfip;
	private Date inicio;
	private Date fin;
	private String backup;
	private Date consolidado;
	private Set<Resultado> resultados = new HashSet<Resultado>(0);

	public Proceso() {
	}

	public Proceso(int iden, String idfip, Date inicio) {
		this.iden = iden;
		this.idfip = idfip;
		this.inicio = inicio;
	}

	public Proceso(int iden, String idfip, Date inicio, Date fin,
			String backup, Date consolidado, Set<Resultado> resultados) {
		this.iden = iden;
		this.idfip = idfip;
		this.inicio = inicio;
		this.fin = fin;
		this.backup = backup;
		this.consolidado = consolidado;
		this.resultados = resultados;
	}

	@SequenceGenerator(name="proceso_seq", sequenceName="validacion.validacion_proceso_sequence")
	@Id
	@GeneratedValue(generator="proceso_seq")
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@Column(name = "idfip", nullable = false, length = 256)
	public String getIdfip() {
		return this.idfip;
	}

	public void setIdfip(String idfip) {
		this.idfip = idfip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inicio", nullable = false, length = 35)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fin", length = 35)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "backup", length = 3000)
	public String getBackup() {
		return this.backup;
	}

	public void setBackup(String backup) {
		this.backup = backup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "consolidado", length = 35)
	public Date getConsolidado() {
		return this.consolidado;
	}

	public void setConsolidado(Date consolidado) {
		this.consolidado = consolidado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<Resultado> getResultados() {
		return this.resultados;
	}

	public void setResultados(Set<Resultado> resultados) {
		this.resultados = resultados;
	}

}
