package es.mitc.redes.urbanismoenred.data.rpm.ficha;

// Generated 21-nov-2011 17:20:25 by Hibernate Tools 3.4.0.CR1

/**
 * Conjuntodeterminaciongrupo generated by hbm2java
 */
public class Conjuntodeterminaciongrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -744197729614003925L;
	private long iden;
	private Conjuntogrupo conjuntogrupo;
	private long iddeterminacion;
	private long orden;

	public Conjuntodeterminaciongrupo() {
	}

	public Conjuntodeterminaciongrupo(long iden, Conjuntogrupo conjuntogrupo,
			long iddeterminacion, long orden) {
		this.iden = iden;
		this.conjuntogrupo = conjuntogrupo;
		this.iddeterminacion = iddeterminacion;
		this.orden = orden;
	}

	public long getIden() {
		return this.iden;
	}

	public void setIden(long iden) {
		this.iden = iden;
	}

	public Conjuntogrupo getConjuntogrupo() {
		return this.conjuntogrupo;
	}

	public void setConjuntogrupo(Conjuntogrupo conjuntogrupo) {
		this.conjuntogrupo = conjuntogrupo;
	}

	public long getIddeterminacion() {
		return this.iddeterminacion;
	}

	public void setIddeterminacion(long iddeterminacion) {
		this.iddeterminacion = iddeterminacion;
	}

	public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}

}
