package es.mitc.redes.urbanismoenred.data.rpm.ficha;

// Generated 21-nov-2011 17:20:25 by Hibernate Tools 3.4.0.CR1

/**
 * Fichagrupodeterminacion generated by hbm2java
 */
public class Fichagrupodeterminacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -561680469340619738L;
	private long iden;
	private Grupodeterminacion grupodeterminacion;
	private Ficha ficha;
	private long orden;

	public Fichagrupodeterminacion() {
	}

	public Fichagrupodeterminacion(long iden,
			Grupodeterminacion grupodeterminacion, Ficha ficha, long orden) {
		this.iden = iden;
		this.grupodeterminacion = grupodeterminacion;
		this.ficha = ficha;
		this.orden = orden;
	}

	public long getIden() {
		return this.iden;
	}

	public void setIden(long iden) {
		this.iden = iden;
	}

	public Grupodeterminacion getGrupodeterminacion() {
		return this.grupodeterminacion;
	}

	public void setGrupodeterminacion(Grupodeterminacion grupodeterminacion) {
		this.grupodeterminacion = grupodeterminacion;
	}

	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}

}
