package es.mitc.redes.urbanismoenred.data.rpm.ficha;

// Generated 21-nov-2011 17:20:25 by Hibernate Tools 3.4.0.CR1

/**
 * Regimenesuso generated by hbm2java
 */
public class Regimenesuso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6743186432774401829L;
	private long iden;
	private Ficha ficha;
	private long iddeterminacion;
        private long orden;
        
	public Regimenesuso() {
	}

	public Regimenesuso(long iden, Ficha ficha, long iddeterminacion,long orden) {
		this.iden = iden;
		this.ficha = ficha;
		this.iddeterminacion = iddeterminacion;
                this.orden = orden;
	}

	public long getIden() {
		return this.iden;
	}

	public void setIden(long iden) {
		this.iden = iden;
	}

	public Ficha getFicha() {
		return this.ficha;
	}

	public void setFicha(Ficha ficha) {
		this.ficha = ficha;
	}

	public long getIddeterminacion() {
		return this.iddeterminacion;
	}

	public void setIddeterminacion(long iddeterminacion) {
		this.iddeterminacion = iddeterminacion;
	}

        public long getOrden() {
		return this.orden;
	}

	public void setOrden(long orden) {
		this.orden = orden;
	}
}
