package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Documentoshp generated by hbm2java
 */
@Entity
@Table(name = "documentoshp")
public class Documentoshp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2758539039704069993L;
	private int iden;
	private Documento documento;
	private String geom;
	private String hoja;

	public Documentoshp() {
	}

	public Documentoshp(int iden, String hoja) {
		this.iden = iden;
		this.hoja = hoja;
	}

	public Documentoshp(int iden, Documento documento, String geom,
			String hoja) {
		this.iden = iden;
		this.documento = documento;
		this.geom = geom;
		this.hoja = hoja;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocumento")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "geom")
	public String getGeom() {
		return this.geom;
	}

	public void setGeom(String geom) {
		this.geom = geom;
	}

	@Column(name = "hoja", nullable = false, length = 100)
	public String getHoja() {
		return this.hoja;
	}

	public void setHoja(String hoja) {
		this.hoja = hoja;
	}

}
