//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 03:59:02 PM CEST 
//


package es.mitc.redes.urbanismoenred.data.fip;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Valor que adopta un caso
 * 
 * <p>Java class for Regimen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Regimen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="COMENTARIO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="REGIMENES-ESPECIFICOS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="REGIMEN-ESPECIFICO" type="{}RegimenEspecifico" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="VALOR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="VALOR-REFERENCIA" type="{}CodigoDeterminacion" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="DETERMINACION-REGIMEN" type="{}CodigoDeterminacion" minOccurs="0"/>
 *         &lt;element name="CASO-APLICACION" type="{}CodigoCaso" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="superposicion" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Regimen", propOrder = {
    "comentario",
    "regimenesespecificos",
    "valor",
    "valorreferencia",
    "determinacionregimen",
    "casoaplicacion"
})
public class Regimen {

    @XmlElement(name = "COMENTARIO")
    protected String comentario;
    @XmlElement(name = "REGIMENES-ESPECIFICOS")
    protected Regimen.REGIMENESESPECIFICOS regimenesespecificos;
    @XmlElement(name = "VALOR")
    protected String valor;
    @XmlElement(name = "VALOR-REFERENCIA")
    protected CodigoDeterminacion valorreferencia;
    @XmlElement(name = "DETERMINACION-REGIMEN")
    protected CodigoDeterminacion determinacionregimen;
    @XmlElement(name = "CASO-APLICACION")
    protected CodigoCaso casoaplicacion;
    @XmlAttribute(name = "superposicion")
    protected BigInteger superposicion;

    /**
     * Gets the value of the comentario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMENTARIO() {
        return comentario;
    }

    /**
     * Sets the value of the comentario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMENTARIO(String value) {
        this.comentario = value;
    }

    /**
     * Gets the value of the regimenesespecificos property.
     * 
     * @return
     *     possible object is
     *     {@link Regimen.REGIMENESESPECIFICOS }
     *     
     */
    public Regimen.REGIMENESESPECIFICOS getREGIMENESESPECIFICOS() {
        return regimenesespecificos;
    }

    /**
     * Sets the value of the regimenesespecificos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regimen.REGIMENESESPECIFICOS }
     *     
     */
    public void setREGIMENESESPECIFICOS(Regimen.REGIMENESESPECIFICOS value) {
        this.regimenesespecificos = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALOR() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALOR(String value) {
        this.valor = value;
    }

    /**
     * Gets the value of the valorreferencia property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getVALORREFERENCIA() {
        return valorreferencia;
    }

    /**
     * Sets the value of the valorreferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setVALORREFERENCIA(CodigoDeterminacion value) {
        this.valorreferencia = value;
    }

    /**
     * Gets the value of the determinacionregimen property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public CodigoDeterminacion getDETERMINACIONREGIMEN() {
        return determinacionregimen;
    }

    /**
     * Sets the value of the determinacionregimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoDeterminacion }
     *     
     */
    public void setDETERMINACIONREGIMEN(CodigoDeterminacion value) {
        this.determinacionregimen = value;
    }

    /**
     * Gets the value of the casoaplicacion property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoCaso }
     *     
     */
    public CodigoCaso getCASOAPLICACION() {
        return casoaplicacion;
    }

    /**
     * Sets the value of the casoaplicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoCaso }
     *     
     */
    public void setCASOAPLICACION(CodigoCaso value) {
        this.casoaplicacion = value;
    }

    /**
     * Gets the value of the superposicion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuperposicion() {
        return superposicion;
    }

    /**
     * Sets the value of the superposicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuperposicion(BigInteger value) {
        this.superposicion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="REGIMEN-ESPECIFICO" type="{}RegimenEspecifico" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regimenespecifico"
    })
    public static class REGIMENESESPECIFICOS {

        @XmlElement(name = "REGIMEN-ESPECIFICO", required = true)
        protected List<RegimenEspecifico> regimenespecifico;

        /**
         * Gets the value of the regimenespecifico property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the regimenespecifico property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getREGIMENESPECIFICO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RegimenEspecifico }
         * 
         * 
         */
        public List<RegimenEspecifico> getREGIMENESPECIFICO() {
            if (regimenespecifico == null) {
                regimenespecifico = new ArrayList<RegimenEspecifico>();
            }
            return this.regimenespecifico;
        }

    }

}
