/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;


/**
 * Caracterdeterminacion generated by hbm2java
 */
public class Caracterdeterminacion implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4301367473749307090L;
	private int iden;
    private Literal literal;
    private Integer nmaxaplicaciones;
    private Integer nminaplicaciones;
    private Set<Operacioncaracter> operacioncaractersForIdcaracteroperado = new HashSet<Operacioncaracter>(0);
    private Set<Operacioncaracter> operacioncaractersForIdcaracteroperador = new HashSet<Operacioncaracter>(0);

    public Caracterdeterminacion() {
    }

    public Caracterdeterminacion(int iden) {
        this.iden = iden;
    }

    public Caracterdeterminacion(int iden, Literal literal, Integer nmaxaplicaciones, Integer nminaplicaciones, Set<Operacioncaracter> operacioncaractersForIdcaracteroperado, Set<Operacioncaracter> operacioncaractersForIdcaracteroperador) {
        this.iden = iden;
        this.literal = literal;
        this.nmaxaplicaciones = nmaxaplicaciones;
        this.nminaplicaciones = nminaplicaciones;
        this.operacioncaractersForIdcaracteroperado = operacioncaractersForIdcaracteroperado;
        this.operacioncaractersForIdcaracteroperador = operacioncaractersForIdcaracteroperador;
    }

    public int getIden() {
        return this.iden;
    }

    public void setIden(int iden) {
        this.iden = iden;
    }

    public Literal getLiteral() {
        return this.literal;
    }

    public void setLiteral(Literal literal) {
        this.literal = literal;
    }

    public Integer getNmaxaplicaciones() {
        return this.nmaxaplicaciones;
    }

    public void setNmaxaplicaciones(Integer nmaxaplicaciones) {
        this.nmaxaplicaciones = nmaxaplicaciones;
    }

    public Integer getNminaplicaciones() {
        return this.nminaplicaciones;
    }

    public void setNminaplicaciones(Integer nminaplicaciones) {
        this.nminaplicaciones = nminaplicaciones;
    }

    public Set<Operacioncaracter> getOperacioncaractersForIdcaracteroperado() {
        return this.operacioncaractersForIdcaracteroperado;
    }

    public void setOperacioncaractersForIdcaracteroperado(Set<Operacioncaracter> operacioncaractersForIdcaracteroperado) {
        this.operacioncaractersForIdcaracteroperado = operacioncaractersForIdcaracteroperado;
    }

    public Set<Operacioncaracter> getOperacioncaractersForIdcaracteroperador() {
        return this.operacioncaractersForIdcaracteroperador;
    }

    public void setOperacioncaractersForIdcaracteroperador(Set<Operacioncaracter> operacioncaractersForIdcaracteroperador) {
        this.operacioncaractersForIdcaracteroperador = operacioncaractersForIdcaracteroperador;
    }
}


