package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regimenespecifico generated by hbm2java
 */
@Entity
@Table(name = "regimenespecifico")
public class Regimenespecifico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8572203649879414949L;
	private int iden;
	private Entidaddeterminacionregimen entidaddeterminacionregimen;
	private Regimenespecifico regimenespecifico;
	private int orden;
	private String nombre;
	private String texto;
	private Set<Regimenespecifico> regimenespecificos = new HashSet<Regimenespecifico>(
			0);

	public Regimenespecifico() {
	}

	public Regimenespecifico(int iden,
			Entidaddeterminacionregimen entidaddeterminacionregimen, int orden) {
		this.iden = iden;
		this.entidaddeterminacionregimen = entidaddeterminacionregimen;
		this.orden = orden;
	}

	public Regimenespecifico(int iden,
			Entidaddeterminacionregimen entidaddeterminacionregimen,
			Regimenespecifico regimenespecifico, int orden, String nombre,
			String texto, Set<Regimenespecifico> regimenespecificos) {
		this.iden = iden;
		this.entidaddeterminacionregimen = entidaddeterminacionregimen;
		this.regimenespecifico = regimenespecifico;
		this.orden = orden;
		this.nombre = nombre;
		this.texto = texto;
		this.regimenespecificos = regimenespecificos;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identidaddeterminacionregimen", nullable = false)
	public Entidaddeterminacionregimen getEntidaddeterminacionregimen() {
		return this.entidaddeterminacionregimen;
	}

	public void setEntidaddeterminacionregimen(
			Entidaddeterminacionregimen entidaddeterminacionregimen) {
		this.entidaddeterminacionregimen = entidaddeterminacionregimen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpadre")
	public Regimenespecifico getRegimenespecifico() {
		return this.regimenespecifico;
	}

	public void setRegimenespecifico(Regimenespecifico regimenespecifico) {
		this.regimenespecifico = regimenespecifico;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regimenespecifico")
	public Set<Regimenespecifico> getRegimenespecificos() {
		return this.regimenespecificos;
	}

	public void setRegimenespecificos(Set<Regimenespecifico> regimenespecificos) {
		this.regimenespecificos = regimenespecificos;
	}

}
