package es.mitc.redes.urbanismoenred.data.rpm.ficha;

// Generated 21-nov-2011 17:20:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Conjuntogrupo generated by hbm2java
 */
public class Conjuntogrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6394002544461255311L;
	private long iden;
	private String nombre;
	private Set<Conjuntodeterminaciongrupo> conjuntodeterminaciongrupos = new HashSet<Conjuntodeterminaciongrupo>(
			0);
	private Set<Fichaconjuntogrupo> fichaconjuntogrupos = new HashSet<Fichaconjuntogrupo>(
			0);
	private Set<Grupodeterminacion> grupodeterminacions = new HashSet<Grupodeterminacion>(
			0);

	public Conjuntogrupo() {
	}

	public Conjuntogrupo(long iden, String nombre) {
		this.iden = iden;
		this.nombre = nombre;
	}

	public Conjuntogrupo(long iden, String nombre,
			Set<Conjuntodeterminaciongrupo> conjuntodeterminaciongrupos,
			Set<Fichaconjuntogrupo> fichaconjuntogrupos,
			Set<Grupodeterminacion> grupodeterminacions) {
		this.iden = iden;
		this.nombre = nombre;
		this.conjuntodeterminaciongrupos = conjuntodeterminaciongrupos;
		this.fichaconjuntogrupos = fichaconjuntogrupos;
		this.grupodeterminacions = grupodeterminacions;
	}

	public long getIden() {
		return this.iden;
	}

	public void setIden(long iden) {
		this.iden = iden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Conjuntodeterminaciongrupo> getConjuntodeterminaciongrupos() {
		return this.conjuntodeterminaciongrupos;
	}

	public void setConjuntodeterminaciongrupos(
			Set<Conjuntodeterminaciongrupo> conjuntodeterminaciongrupos) {
		this.conjuntodeterminaciongrupos = conjuntodeterminaciongrupos;
	}

	public Set<Fichaconjuntogrupo> getFichaconjuntogrupos() {
		return this.fichaconjuntogrupos;
	}

	public void setFichaconjuntogrupos(
			Set<Fichaconjuntogrupo> fichaconjuntogrupos) {
		this.fichaconjuntogrupos = fichaconjuntogrupos;
	}

	public Set<Grupodeterminacion> getGrupodeterminacions() {
		return this.grupodeterminacions;
	}

	public void setGrupodeterminacions(
			Set<Grupodeterminacion> grupodeterminacions) {
		this.grupodeterminacions = grupodeterminacions;
	}

}
