package es.mitc.redes.urbanismoenred.data.rpm.ficha;

// Generated 21-nov-2011 17:20:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ficha generated by hbm2java
 */
public class Ficha implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9104153779421498976L;
	private long iden;
	private String nombre;
	private String path;
	private long idtramite;
	private String xpath;
	private Set<Determinacionclasifacto> determinacionclasifactos = new HashSet<Determinacionclasifacto>(
			0);
	private Set<Regimenesuso> regimenesusos = new HashSet<Regimenesuso>(0);
	private Set<Regimenesacto> regimenesactos = new HashSet<Regimenesacto>(0);
	private Set<Fichagrupodeterminacion> fichagrupodeterminacions = new HashSet<Fichagrupodeterminacion>(
			0);
	private Set<Fichaconjuntogrupo> fichaconjuntogrupos = new HashSet<Fichaconjuntogrupo>(
			0);
	private Set<Determinacionclasifuso> determinacionclasifusos = new HashSet<Determinacionclasifuso>(
			0);

	public Ficha() {
	}

	public Ficha(long iden, String nombre, String path, long idtramite,
			String xpath) {
		this.iden = iden;
		this.nombre = nombre;
		this.path = path;
		this.idtramite = idtramite;
		this.xpath = xpath;
	}

	public Ficha(long iden, String nombre, String path, long idtramite,
			String xpath,
			Set<Determinacionclasifacto> determinacionclasifactos,
			Set<Regimenesuso> regimenesusos, Set<Regimenesacto> regimenesactos,
			Set<Fichagrupodeterminacion> fichagrupodeterminacions,
			Set<Fichaconjuntogrupo> fichaconjuntogrupos,
			Set<Determinacionclasifuso> determinacionclasifusos) {
		this.iden = iden;
		this.nombre = nombre;
		this.path = path;
		this.idtramite = idtramite;
		this.xpath = xpath;
		this.determinacionclasifactos = determinacionclasifactos;
		this.regimenesusos = regimenesusos;
		this.regimenesactos = regimenesactos;
		this.fichagrupodeterminacions = fichagrupodeterminacions;
		this.fichaconjuntogrupos = fichaconjuntogrupos;
		this.determinacionclasifusos = determinacionclasifusos;
	}

	public long getIden() {
		return this.iden;
	}

	public void setIden(long iden) {
		this.iden = iden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public long getIdtramite() {
		return this.idtramite;
	}

	public void setIdtramite(long idtramite) {
		this.idtramite = idtramite;
	}

	public String getXpath() {
		return this.xpath;
	}

	public void setXpath(String xpath) {
		this.xpath = xpath;
	}

	public Set<Determinacionclasifacto> getDeterminacionclasifactos() {
		return this.determinacionclasifactos;
	}

	public void setDeterminacionclasifactos(
			Set<Determinacionclasifacto> determinacionclasifactos) {
		this.determinacionclasifactos = determinacionclasifactos;
	}

	public Set<Regimenesuso> getRegimenesusos() {
		return this.regimenesusos;
	}

	public void setRegimenesusos(Set<Regimenesuso> regimenesusos) {
		this.regimenesusos = regimenesusos;
	}

	public Set<Regimenesacto> getRegimenesactos() {
		return this.regimenesactos;
	}

	public void setRegimenesactos(Set<Regimenesacto> regimenesactos) {
		this.regimenesactos = regimenesactos;
	}

	public Set<Fichagrupodeterminacion> getFichagrupodeterminacions() {
		return this.fichagrupodeterminacions;
	}

	public void setFichagrupodeterminacions(
			Set<Fichagrupodeterminacion> fichagrupodeterminacions) {
		this.fichagrupodeterminacions = fichagrupodeterminacions;
	}

	public Set<Fichaconjuntogrupo> getFichaconjuntogrupos() {
		return this.fichaconjuntogrupos;
	}

	public void setFichaconjuntogrupos(
			Set<Fichaconjuntogrupo> fichaconjuntogrupos) {
		this.fichaconjuntogrupos = fichaconjuntogrupos;
	}

	public Set<Determinacionclasifuso> getDeterminacionclasifusos() {
		return this.determinacionclasifusos;
	}

	public void setDeterminacionclasifusos(
			Set<Determinacionclasifuso> determinacionclasifusos) {
		this.determinacionclasifusos = determinacionclasifusos;
	}

}
