/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.diccionario;
// Generated 08-jul-2009 12:36:15 by Hibernate Tools 3.2.1.GA


import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Tipooperaciondeterminacion generated by hbm2java
 */
public class Tipooperaciondeterminacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5384200789944519000L;
	private int iden;
     private Literal literal;
     private Set<Operacioncaracter> operacioncaracters = new HashSet<Operacioncaracter>(0);

    public Tipooperaciondeterminacion() {
    }

	
    public Tipooperaciondeterminacion(int iden) {
        this.iden = iden;
    }
    public Tipooperaciondeterminacion(int iden, Literal literal, Set<Operacioncaracter> operacioncaracters) {
       this.iden = iden;
       this.literal = literal;
       this.operacioncaracters = operacioncaracters;
    }
   
    public int getIden() {
        return this.iden;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public Literal getLiteral() {
        return this.literal;
    }
    
    public void setLiteral(Literal literal) {
        this.literal = literal;
    }
    public Set<Operacioncaracter> getOperacioncaracters() {
        return this.operacioncaracters;
    }
    
    public void setOperacioncaracters(Set<Operacioncaracter> operacioncaracters) {
        this.operacioncaracters = operacioncaracters;
    }

    public Map<String, Object> toJSON(String idioma) {
        Map<String, Object> res = new HashMap<String, Object>();
        try {

            res.put("iden", this.getIden());
            res.put("nombre", this.getLiteral().getTexto(idioma));
            
        } catch (Exception e) {
            Logger.getLogger(Tipooperaciondeterminacion.class.toString()).log(Level.SEVERE,"Error al consultar el Tipo Operación de Determinación "+this.getIden(), e);
        }

        return res;
    }




}


