/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/

// Generated 18-jul-2011 17:35:19 by Hibernate Tools 3.4.0.CR1
package com.mitc.redes.editorfip.entidades.rpm.validacion;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Error generated by hbm2java
 */
@Entity
@Table(name = "error", schema="validacion")
public class Error implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5819717996482304979L;
	private int iden;
	private Resultado resultado;
	private String mensaje;

	public Error() {
	}

	public Error(int iden, Resultado resultado, String mensaje) {
		this.iden = iden;
		this.resultado = resultado;
		this.mensaje = mensaje;
	}

	@SequenceGenerator(name="error_seq", sequenceName="validacion.validacion_error_sequence")
	@Id
	@GeneratedValue(generator="error_seq")
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "idproceso", referencedColumnName = "idproceso", nullable = false),
			@JoinColumn(name = "idvalidacion", referencedColumnName = "idvalidacion", nullable = false) })
	public Resultado getResultado() {
		return this.resultado;
	}

	public void setResultado(Resultado resultado) {
		this.resultado = resultado;
	}

	@Column(name = "mensaje", nullable = false, length = 1000)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
