/*
* Copyright 2011 red.es
* Autores: Arnaiz Consultores.
*
** Licencia con arreglo a la EUPL, Versión 1.1 o -en cuanto
** sean aprobadas por la Comision Europea- versiones
** posteriores de la EUPL (la <<Licencia>>);
** Solo podra usarse esta obra si se respeta la Licencia.
* Puede obtenerse una copia de la Licencia en:
*
* http://ec.europa.eu/idabc/eupl5
*
** Salvo cuando lo exija la legislacion aplicable o se acuerde
* por escrito, el programa distribuido con arreglo a la
* Licencia se distribuye <<TAL CUAL>>,
** SIN GARANTIAS NI CONDICIONES DE NINGUN TIPO, ni expresas
** ni implicitas.
** Vease la Licencia en el idioma concreto que rige
* los permisos y limitaciones que establece la Licencia.
*/
package es.mitc.redes.urbanismoenred.data.rpm.planeamiento;
// Generated 27-jul-2009 13:12:50 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Casoentidaddeterminacion generated by hbm2java
 */
public class Casoentidaddeterminacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5065255361301724171L;
	private int iden;
     private Entidaddeterminacion entidaddeterminacion;
     private String nombre;
     private int orden;
     private Set<Documentocaso> documentocasos = new HashSet<Documentocaso>(0);
     private Set<Vinculocaso> vinculocasosForIdcaso = new HashSet<Vinculocaso>(0);
     private Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcaso = new HashSet<Entidaddeterminacionregimen>(0);
     private Set<Vinculocaso> vinculocasosForIdcasovinculado = new HashSet<Vinculocaso>(0);
     private Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcasoaplicacion = new HashSet<Entidaddeterminacionregimen>(0);

    public Casoentidaddeterminacion() {
    }

	
    public Casoentidaddeterminacion(int iden, Entidaddeterminacion entidaddeterminacion) {
        this.iden = iden;
        this.entidaddeterminacion = entidaddeterminacion;
    }
    public Casoentidaddeterminacion(int iden, Entidaddeterminacion entidaddeterminacion, String nombre, Set<Documentocaso> documentocasos, Set<Vinculocaso> vinculocasosForIdcaso, Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcaso, Set<Vinculocaso> vinculocasosForIdcasovinculado, Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcasoaplicacion) {
       this.iden = iden;
       this.entidaddeterminacion = entidaddeterminacion;
       this.nombre = nombre;
       this.documentocasos = documentocasos;
       this.vinculocasosForIdcaso = vinculocasosForIdcaso;
       this.entidaddeterminacionregimensForIdcaso = entidaddeterminacionregimensForIdcaso;
       this.vinculocasosForIdcasovinculado = vinculocasosForIdcasovinculado;
       this.entidaddeterminacionregimensForIdcasoaplicacion = entidaddeterminacionregimensForIdcasoaplicacion;
    }

        public Set<Documentocaso> getDocumentocasos() {
		    return this.documentocasos;
		}
    
    public Entidaddeterminacion getEntidaddeterminacion() {
        return this.entidaddeterminacion;
    }
    public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimensForIdcaso() {
        return this.entidaddeterminacionregimensForIdcaso;
    }
    
    public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimensForIdcasoaplicacion() {
        return this.entidaddeterminacionregimensForIdcasoaplicacion;
    }
    public int getIden() {
	return this.iden;
   }
    
    public String getNombre() {
        return this.nombre;
    }
    /**
	 * @return the orden
	 */
	public int getOrden() {
		return orden;
	}
    
    public Set<Vinculocaso> getVinculocasosForIdcaso() {
        return this.vinculocasosForIdcaso;
    }
    public Set<Vinculocaso> getVinculocasosForIdcasovinculado() {
        return this.vinculocasosForIdcasovinculado;
    }
    
    public void setDocumentocasos(Set<Documentocaso> documentocasos) {
        this.documentocasos = documentocasos;
    }
    public void setEntidaddeterminacion(Entidaddeterminacion entidaddeterminacion) {
        this.entidaddeterminacion = entidaddeterminacion;
    }
    
    public void setEntidaddeterminacionregimensForIdcaso(Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcaso) {
        this.entidaddeterminacionregimensForIdcaso = entidaddeterminacionregimensForIdcaso;
    }
    public void setEntidaddeterminacionregimensForIdcasoaplicacion(Set<Entidaddeterminacionregimen> entidaddeterminacionregimensForIdcasoaplicacion) {
        this.entidaddeterminacionregimensForIdcasoaplicacion = entidaddeterminacionregimensForIdcasoaplicacion;
    }
    
    public void setIden(int iden) {
        this.iden = iden;
    }
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    /**
	 * @param orden the orden to set
	 */
	public void setOrden(int orden) {
		this.orden = orden;
	}


	public void setVinculocasosForIdcaso(Set<Vinculocaso> vinculocasosForIdcaso) {
        this.vinculocasosForIdcaso = vinculocasosForIdcaso;
    }


	public void setVinculocasosForIdcasovinculado(Set<Vinculocaso> vinculocasosForIdcasovinculado) {
        this.vinculocasosForIdcasovinculado = vinculocasosForIdcasovinculado;
    }




}


