package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name = "archivo")
public class Archivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4692907831568837079L;
	private int iden;
	private Proceso proceso;
	private String tipo;
	private String contenido;

	public Archivo() {
	}

	public Archivo(int iden, Proceso proceso, String tipo, String contenido) {
		this.iden = iden;
		this.proceso = proceso;
		this.tipo = tipo;
		this.contenido = contenido;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proceso", nullable = false)
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	@Column(name = "tipo", nullable = false, length = 256)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "contenido", nullable = false, length = 1000)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

}
