package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Determinacion generated by hbm2java
 */
@Entity
@Table(name = "determinacion")
public class Determinacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7084222605983098055L;
	private int iden;
	private Tramite tramite;
	private Determinacion determinacionByIddeterminacionoriginal;
	private Determinacion determinacionByIdpadre;
	private Determinacion determinacionByIddeterminacionbase;
	private int idcaracter;
	private String apartado;
	private String nombre;
	private String texto;
	private String etiqueta;
	private String codigo;
	private boolean bsuspendida;
	private int orden;
	private Set<Documentodeterminacion> documentodeterminacions = new HashSet<Documentodeterminacion>(
			0);
	private Set<Determinacion> determinacionsForIdpadre = new HashSet<Determinacion>(
			0);
	private Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminaciongrupo = new HashSet<Determinaciongrupoentidad>(
			0);
	private Set<Determinacion> determinacionsForIddeterminacionbase = new HashSet<Determinacion>(
			0);
	private Set<Opciondeterminacion> opciondeterminacionsForIddeterminacion = new HashSet<Opciondeterminacion>(
			0);
	private Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacionoperadora = new HashSet<Operaciondeterminacion>(
			0);
	private Set<Opciondeterminacion> opciondeterminacionsForIddeterminacionvalorref = new HashSet<Opciondeterminacion>(
			0);
	private Set<Determinacion> determinacionsForIddeterminacionoriginal = new HashSet<Determinacion>(
			0);
	private Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminacion = new HashSet<Determinaciongrupoentidad>(
			0);
	private Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacion = new HashSet<Operaciondeterminacion>(
			0);
	private Set<Entidaddeterminacionregimen> entidaddeterminacionregimens = new HashSet<Entidaddeterminacionregimen>(
			0);
	private Set<Entidaddeterminacion> entidaddeterminacions = new HashSet<Entidaddeterminacion>(
			0);

	public Determinacion() {
	}

	public Determinacion(int iden, Tramite tramite, int idcaracter,
			String nombre, String codigo, boolean bsuspendida, int orden) {
		this.iden = iden;
		this.tramite = tramite;
		this.idcaracter = idcaracter;
		this.nombre = nombre;
		this.codigo = codigo;
		this.bsuspendida = bsuspendida;
		this.orden = orden;
	}

	public Determinacion(
			int iden,
			Tramite tramite,
			Determinacion determinacionByIddeterminacionoriginal,
			Determinacion determinacionByIdpadre,
			Determinacion determinacionByIddeterminacionbase,
			int idcaracter,
			String apartado,
			String nombre,
			String texto,
			String etiqueta,
			String codigo,
			boolean bsuspendida,
			int orden,
			Set<Documentodeterminacion> documentodeterminacions,
			Set<Determinacion> determinacionsForIdpadre,
			Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminaciongrupo,
			Set<Determinacion> determinacionsForIddeterminacionbase,
			Set<Opciondeterminacion> opciondeterminacionsForIddeterminacion,
			Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacionoperadora,
			Set<Opciondeterminacion> opciondeterminacionsForIddeterminacionvalorref,
			Set<Determinacion> determinacionsForIddeterminacionoriginal,
			Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminacion,
			Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacion,
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimens,
			Set<Entidaddeterminacion> entidaddeterminacions) {
		this.iden = iden;
		this.tramite = tramite;
		this.determinacionByIddeterminacionoriginal = determinacionByIddeterminacionoriginal;
		this.determinacionByIdpadre = determinacionByIdpadre;
		this.determinacionByIddeterminacionbase = determinacionByIddeterminacionbase;
		this.idcaracter = idcaracter;
		this.apartado = apartado;
		this.nombre = nombre;
		this.texto = texto;
		this.etiqueta = etiqueta;
		this.codigo = codigo;
		this.bsuspendida = bsuspendida;
		this.orden = orden;
		this.documentodeterminacions = documentodeterminacions;
		this.determinacionsForIdpadre = determinacionsForIdpadre;
		this.determinaciongrupoentidadsForIddeterminaciongrupo = determinaciongrupoentidadsForIddeterminaciongrupo;
		this.determinacionsForIddeterminacionbase = determinacionsForIddeterminacionbase;
		this.opciondeterminacionsForIddeterminacion = opciondeterminacionsForIddeterminacion;
		this.operaciondeterminacionsForIddeterminacionoperadora = operaciondeterminacionsForIddeterminacionoperadora;
		this.opciondeterminacionsForIddeterminacionvalorref = opciondeterminacionsForIddeterminacionvalorref;
		this.determinacionsForIddeterminacionoriginal = determinacionsForIddeterminacionoriginal;
		this.determinaciongrupoentidadsForIddeterminacion = determinaciongrupoentidadsForIddeterminacion;
		this.operaciondeterminacionsForIddeterminacion = operaciondeterminacionsForIddeterminacion;
		this.entidaddeterminacionregimens = entidaddeterminacionregimens;
		this.entidaddeterminacions = entidaddeterminacions;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtramite", nullable = false)
	public Tramite getTramite() {
		return this.tramite;
	}

	public void setTramite(Tramite tramite) {
		this.tramite = tramite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminacionoriginal")
	public Determinacion getDeterminacionByIddeterminacionoriginal() {
		return this.determinacionByIddeterminacionoriginal;
	}

	public void setDeterminacionByIddeterminacionoriginal(
			Determinacion determinacionByIddeterminacionoriginal) {
		this.determinacionByIddeterminacionoriginal = determinacionByIddeterminacionoriginal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpadre")
	public Determinacion getDeterminacionByIdpadre() {
		return this.determinacionByIdpadre;
	}

	public void setDeterminacionByIdpadre(Determinacion determinacionByIdpadre) {
		this.determinacionByIdpadre = determinacionByIdpadre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminacionbase")
	public Determinacion getDeterminacionByIddeterminacionbase() {
		return this.determinacionByIddeterminacionbase;
	}

	public void setDeterminacionByIddeterminacionbase(
			Determinacion determinacionByIddeterminacionbase) {
		this.determinacionByIddeterminacionbase = determinacionByIddeterminacionbase;
	}

	@Column(name = "idcaracter", nullable = false)
	public int getIdcaracter() {
		return this.idcaracter;
	}

	public void setIdcaracter(int idcaracter) {
		this.idcaracter = idcaracter;
	}

	@Column(name = "apartado", length = 100)
	public String getApartado() {
		return this.apartado;
	}

	public void setApartado(String apartado) {
		this.apartado = apartado;
	}

	@Column(name = "nombre", nullable = false, length = 220)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "etiqueta", length = 100)
	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	@Column(name = "codigo", nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "bsuspendida", nullable = false)
	public boolean isBsuspendida() {
		return this.bsuspendida;
	}

	public void setBsuspendida(boolean bsuspendida) {
		this.bsuspendida = bsuspendida;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacion")
	public Set<Documentodeterminacion> getDocumentodeterminacions() {
		return this.documentodeterminacions;
	}

	public void setDocumentodeterminacions(
			Set<Documentodeterminacion> documentodeterminacions) {
		this.documentodeterminacions = documentodeterminacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIdpadre")
	public Set<Determinacion> getDeterminacionsForIdpadre() {
		return this.determinacionsForIdpadre;
	}

	public void setDeterminacionsForIdpadre(
			Set<Determinacion> determinacionsForIdpadre) {
		this.determinacionsForIdpadre = determinacionsForIdpadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminaciongrupo")
	public Set<Determinaciongrupoentidad> getDeterminaciongrupoentidadsForIddeterminaciongrupo() {
		return this.determinaciongrupoentidadsForIddeterminaciongrupo;
	}

	public void setDeterminaciongrupoentidadsForIddeterminaciongrupo(
			Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminaciongrupo) {
		this.determinaciongrupoentidadsForIddeterminaciongrupo = determinaciongrupoentidadsForIddeterminaciongrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacionbase")
	public Set<Determinacion> getDeterminacionsForIddeterminacionbase() {
		return this.determinacionsForIddeterminacionbase;
	}

	public void setDeterminacionsForIddeterminacionbase(
			Set<Determinacion> determinacionsForIddeterminacionbase) {
		this.determinacionsForIddeterminacionbase = determinacionsForIddeterminacionbase;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacion")
	public Set<Opciondeterminacion> getOpciondeterminacionsForIddeterminacion() {
		return this.opciondeterminacionsForIddeterminacion;
	}

	public void setOpciondeterminacionsForIddeterminacion(
			Set<Opciondeterminacion> opciondeterminacionsForIddeterminacion) {
		this.opciondeterminacionsForIddeterminacion = opciondeterminacionsForIddeterminacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacionoperadora")
	public Set<Operaciondeterminacion> getOperaciondeterminacionsForIddeterminacionoperadora() {
		return this.operaciondeterminacionsForIddeterminacionoperadora;
	}

	public void setOperaciondeterminacionsForIddeterminacionoperadora(
			Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacionoperadora) {
		this.operaciondeterminacionsForIddeterminacionoperadora = operaciondeterminacionsForIddeterminacionoperadora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacionvalorref")
	public Set<Opciondeterminacion> getOpciondeterminacionsForIddeterminacionvalorref() {
		return this.opciondeterminacionsForIddeterminacionvalorref;
	}

	public void setOpciondeterminacionsForIddeterminacionvalorref(
			Set<Opciondeterminacion> opciondeterminacionsForIddeterminacionvalorref) {
		this.opciondeterminacionsForIddeterminacionvalorref = opciondeterminacionsForIddeterminacionvalorref;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacionoriginal")
	public Set<Determinacion> getDeterminacionsForIddeterminacionoriginal() {
		return this.determinacionsForIddeterminacionoriginal;
	}

	public void setDeterminacionsForIddeterminacionoriginal(
			Set<Determinacion> determinacionsForIddeterminacionoriginal) {
		this.determinacionsForIddeterminacionoriginal = determinacionsForIddeterminacionoriginal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacion")
	public Set<Determinaciongrupoentidad> getDeterminaciongrupoentidadsForIddeterminacion() {
		return this.determinaciongrupoentidadsForIddeterminacion;
	}

	public void setDeterminaciongrupoentidadsForIddeterminacion(
			Set<Determinaciongrupoentidad> determinaciongrupoentidadsForIddeterminacion) {
		this.determinaciongrupoentidadsForIddeterminacion = determinaciongrupoentidadsForIddeterminacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacionByIddeterminacion")
	public Set<Operaciondeterminacion> getOperaciondeterminacionsForIddeterminacion() {
		return this.operaciondeterminacionsForIddeterminacion;
	}

	public void setOperaciondeterminacionsForIddeterminacion(
			Set<Operaciondeterminacion> operaciondeterminacionsForIddeterminacion) {
		this.operaciondeterminacionsForIddeterminacion = operaciondeterminacionsForIddeterminacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacion")
	public Set<Entidaddeterminacionregimen> getEntidaddeterminacionregimens() {
		return this.entidaddeterminacionregimens;
	}

	public void setEntidaddeterminacionregimens(
			Set<Entidaddeterminacionregimen> entidaddeterminacionregimens) {
		this.entidaddeterminacionregimens = entidaddeterminacionregimens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "determinacion")
	public Set<Entidaddeterminacion> getEntidaddeterminacions() {
		return this.entidaddeterminacions;
	}

	public void setEntidaddeterminacions(
			Set<Entidaddeterminacion> entidaddeterminacions) {
		this.entidaddeterminacions = entidaddeterminacions;
	}

}
