package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Determinaciongrupoentidad generated by hbm2java
 */
@Entity
@Table(name = "determinaciongrupoentidad")
public class Determinaciongrupoentidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6424931570855129306L;
	private int iden;
	private Determinacion determinacionByIddeterminacion;
	private Determinacion determinacionByIddeterminaciongrupo;

	public Determinaciongrupoentidad() {
	}

	public Determinaciongrupoentidad(int iden,
			Determinacion determinacionByIddeterminacion) {
		this.iden = iden;
		this.determinacionByIddeterminacion = determinacionByIddeterminacion;
	}

	public Determinaciongrupoentidad(int iden,
			Determinacion determinacionByIddeterminacion,
			Determinacion determinacionByIddeterminaciongrupo) {
		this.iden = iden;
		this.determinacionByIddeterminacion = determinacionByIddeterminacion;
		this.determinacionByIddeterminaciongrupo = determinacionByIddeterminaciongrupo;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminacion", nullable = false)
	public Determinacion getDeterminacionByIddeterminacion() {
		return this.determinacionByIddeterminacion;
	}

	public void setDeterminacionByIddeterminacion(
			Determinacion determinacionByIddeterminacion) {
		this.determinacionByIddeterminacion = determinacionByIddeterminacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminaciongrupo")
	public Determinacion getDeterminacionByIddeterminaciongrupo() {
		return this.determinacionByIddeterminaciongrupo;
	}

	public void setDeterminacionByIddeterminaciongrupo(
			Determinacion determinacionByIddeterminaciongrupo) {
		this.determinacionByIddeterminaciongrupo = determinacionByIddeterminaciongrupo;
	}

}
