package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Documentocaso generated by hbm2java
 */
@Entity
@Table(name = "documentocaso")
public class Documentocaso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9999368785024374L;
	private int iden;
	private Documento documento;
	private Casoentidaddeterminacion casoentidaddeterminacion;

	public Documentocaso() {
	}

	public Documentocaso(int iden, Documento documento,
			Casoentidaddeterminacion casoentidaddeterminacion) {
		this.iden = iden;
		this.documento = documento;
		this.casoentidaddeterminacion = casoentidaddeterminacion;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocumento", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcaso", nullable = false)
	public Casoentidaddeterminacion getCasoentidaddeterminacion() {
		return this.casoentidaddeterminacion;
	}

	public void setCasoentidaddeterminacion(
			Casoentidaddeterminacion casoentidaddeterminacion) {
		this.casoentidaddeterminacion = casoentidaddeterminacion;
	}

}
