package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento")
public class Documento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9037021659340106791L;
	private int iden;
	private Tramite tramite;
	private Documento documento;
	private String nombre;
	private String archivo;
	private String comentario;
	private Integer escala;
	private Integer idtipodocumento;
	private Integer idgrupodocumento;
	private Set<Documentoentidad> documentoentidads = new HashSet<Documentoentidad>(
			0);
	private Set<Documentocaso> documentocasos = new HashSet<Documentocaso>(0);
	private Set<Documentodeterminacion> documentodeterminacions = new HashSet<Documentodeterminacion>(
			0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<Documentoshp> documentoshps = new HashSet<Documentoshp>(0);

	public Documento() {
	}

	public Documento(int iden, Tramite tramite, String nombre, String archivo) {
		this.iden = iden;
		this.tramite = tramite;
		this.nombre = nombre;
		this.archivo = archivo;
	}

	public Documento(int iden, Tramite tramite, Documento documento,
			String nombre, String archivo, String comentario, Integer escala,
			Integer idtipodocumento, Integer idgrupodocumento,
			Set<Documentoentidad> documentoentidads,
			Set<Documentocaso> documentocasos,
			Set<Documentodeterminacion> documentodeterminacions,
			Set<Documento> documentos, Set<Documentoshp> documentoshps) {
		this.iden = iden;
		this.tramite = tramite;
		this.documento = documento;
		this.nombre = nombre;
		this.archivo = archivo;
		this.comentario = comentario;
		this.escala = escala;
		this.idtipodocumento = idtipodocumento;
		this.idgrupodocumento = idgrupodocumento;
		this.documentoentidads = documentoentidads;
		this.documentocasos = documentocasos;
		this.documentodeterminacions = documentodeterminacions;
		this.documentos = documentos;
		this.documentoshps = documentoshps;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtramite", nullable = false)
	public Tramite getTramite() {
		return this.tramite;
	}

	public void setTramite(Tramite tramite) {
		this.tramite = tramite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocumentooriginal")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "archivo", nullable = false)
	public String getArchivo() {
		return this.archivo;
	}

	public void setArchivo(String archivo) {
		this.archivo = archivo;
	}

	@Column(name = "comentario")
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "escala")
	public Integer getEscala() {
		return this.escala;
	}

	public void setEscala(Integer escala) {
		this.escala = escala;
	}

	@Column(name = "idtipodocumento")
	public Integer getIdtipodocumento() {
		return this.idtipodocumento;
	}

	public void setIdtipodocumento(Integer idtipodocumento) {
		this.idtipodocumento = idtipodocumento;
	}

	@Column(name = "idgrupodocumento")
	public Integer getIdgrupodocumento() {
		return this.idgrupodocumento;
	}

	public void setIdgrupodocumento(Integer idgrupodocumento) {
		this.idgrupodocumento = idgrupodocumento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Documentoentidad> getDocumentoentidads() {
		return this.documentoentidads;
	}

	public void setDocumentoentidads(Set<Documentoentidad> documentoentidads) {
		this.documentoentidads = documentoentidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Documentocaso> getDocumentocasos() {
		return this.documentocasos;
	}

	public void setDocumentocasos(Set<Documentocaso> documentocasos) {
		this.documentocasos = documentocasos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Documentodeterminacion> getDocumentodeterminacions() {
		return this.documentodeterminacions;
	}

	public void setDocumentodeterminacions(
			Set<Documentodeterminacion> documentodeterminacions) {
		this.documentodeterminacions = documentodeterminacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Documentoshp> getDocumentoshps() {
		return this.documentoshps;
	}

	public void setDocumentoshps(Set<Documentoshp> documentoshps) {
		this.documentoshps = documentoshps;
	}

}
