package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Operaciondeterminacion generated by hbm2java
 */
@Entity
@Table(name = "operaciondeterminacion")
public class Operaciondeterminacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1921369944139572171L;
	private int iden;
	private Operacion operacion;
	private Determinacion determinacionByIddeterminacion;
	private Determinacion determinacionByIddeterminacionoperadora;
	private int idtipooperaciondet;

	public Operaciondeterminacion() {
	}

	public Operaciondeterminacion(int iden, Operacion operacion,
			Determinacion determinacionByIddeterminacion,
			Determinacion determinacionByIddeterminacionoperadora,
			int idtipooperaciondet) {
		this.iden = iden;
		this.operacion = operacion;
		this.determinacionByIddeterminacion = determinacionByIddeterminacion;
		this.determinacionByIddeterminacionoperadora = determinacionByIddeterminacionoperadora;
		this.idtipooperaciondet = idtipooperaciondet;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperacion", nullable = false)
	public Operacion getOperacion() {
		return this.operacion;
	}

	public void setOperacion(Operacion operacion) {
		this.operacion = operacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminacion", nullable = false)
	public Determinacion getDeterminacionByIddeterminacion() {
		return this.determinacionByIddeterminacion;
	}

	public void setDeterminacionByIddeterminacion(
			Determinacion determinacionByIddeterminacion) {
		this.determinacionByIddeterminacion = determinacionByIddeterminacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddeterminacionoperadora", nullable = false)
	public Determinacion getDeterminacionByIddeterminacionoperadora() {
		return this.determinacionByIddeterminacionoperadora;
	}

	public void setDeterminacionByIddeterminacionoperadora(
			Determinacion determinacionByIddeterminacionoperadora) {
		this.determinacionByIddeterminacionoperadora = determinacionByIddeterminacionoperadora;
	}

	@Column(name = "idtipooperaciondet", nullable = false)
	public int getIdtipooperaciondet() {
		return this.idtipooperaciondet;
	}

	public void setIdtipooperaciondet(int idtipooperaciondet) {
		this.idtipooperaciondet = idtipooperaciondet;
	}

}
