package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Operacionplan generated by hbm2java
 */
@Entity
@Table(name = "operacionplan")
public class Operacionplan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -889944337789247306L;
	private int iden;
	private Plan planByIdplanoperador;
	private Plan planByIdplanoperado;
	private int idinstrumentotipooperacion;

	public Operacionplan() {
	}

	public Operacionplan(int iden, Plan planByIdplanoperador,
			int idinstrumentotipooperacion) {
		this.iden = iden;
		this.planByIdplanoperador = planByIdplanoperador;
		this.idinstrumentotipooperacion = idinstrumentotipooperacion;
	}

	public Operacionplan(int iden, Plan planByIdplanoperador,
			Plan planByIdplanoperado, int idinstrumentotipooperacion) {
		this.iden = iden;
		this.planByIdplanoperador = planByIdplanoperador;
		this.planByIdplanoperado = planByIdplanoperado;
		this.idinstrumentotipooperacion = idinstrumentotipooperacion;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idplanoperador", nullable = false)
	public Plan getPlanByIdplanoperador() {
		return this.planByIdplanoperador;
	}

	public void setPlanByIdplanoperador(Plan planByIdplanoperador) {
		this.planByIdplanoperador = planByIdplanoperador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idplanoperado")
	public Plan getPlanByIdplanoperado() {
		return this.planByIdplanoperado;
	}

	public void setPlanByIdplanoperado(Plan planByIdplanoperado) {
		this.planByIdplanoperado = planByIdplanoperado;
	}

	@Column(name = "idinstrumentotipooperacion", nullable = false)
	public int getIdinstrumentotipooperacion() {
		return this.idinstrumentotipooperacion;
	}

	public void setIdinstrumentotipooperacion(int idinstrumentotipooperacion) {
		this.idinstrumentotipooperacion = idinstrumentotipooperacion;
	}

}
