package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "plan")
public class Plan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2402775782616802841L;
	private int iden;
	private Plan planByIdpadre;
	private Plan planByIdplanbase;
	private String nombre;
	private String codigo;
	private String texto;
	private int idambito;
	private boolean bsuspendido;
	private int orden;
	private Set<Plan> plansForIdplanbase = new HashSet<Plan>(0);
	private Set<Operacionplan> operacionplansForIdplanoperador = new HashSet<Operacionplan>(
			0);
	private Set<Tramite> tramites = new HashSet<Tramite>(0);
	private Set<Operacionplan> operacionplansForIdplanoperado = new HashSet<Operacionplan>(
			0);
	private Set<Plan> plansForIdpadre = new HashSet<Plan>(0);

	public Plan() {
	}

	public Plan(int iden, String nombre, String codigo, int idambito,
			boolean bsuspendido, int orden) {
		this.iden = iden;
		this.nombre = nombre;
		this.codigo = codigo;
		this.idambito = idambito;
		this.bsuspendido = bsuspendido;
		this.orden = orden;
	}

	public Plan(int iden, Plan planByIdpadre, Plan planByIdplanbase,
			String nombre, String codigo, String texto, int idambito,
			boolean bsuspendido, int orden, Set<Plan> plansForIdplanbase,
			Set<Operacionplan> operacionplansForIdplanoperador,
			Set<Tramite> tramites,
			Set<Operacionplan> operacionplansForIdplanoperado,
			Set<Plan> plansForIdpadre) {
		this.iden = iden;
		this.planByIdpadre = planByIdpadre;
		this.planByIdplanbase = planByIdplanbase;
		this.nombre = nombre;
		this.codigo = codigo;
		this.texto = texto;
		this.idambito = idambito;
		this.bsuspendido = bsuspendido;
		this.orden = orden;
		this.plansForIdplanbase = plansForIdplanbase;
		this.operacionplansForIdplanoperador = operacionplansForIdplanoperador;
		this.tramites = tramites;
		this.operacionplansForIdplanoperado = operacionplansForIdplanoperado;
		this.plansForIdpadre = plansForIdpadre;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpadre")
	public Plan getPlanByIdpadre() {
		return this.planByIdpadre;
	}

	public void setPlanByIdpadre(Plan planByIdpadre) {
		this.planByIdpadre = planByIdpadre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idplanbase")
	public Plan getPlanByIdplanbase() {
		return this.planByIdplanbase;
	}

	public void setPlanByIdplanbase(Plan planByIdplanbase) {
		this.planByIdplanbase = planByIdplanbase;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo", nullable = false, length = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "idambito", nullable = false)
	public int getIdambito() {
		return this.idambito;
	}

	public void setIdambito(int idambito) {
		this.idambito = idambito;
	}

	@Column(name = "bsuspendido", nullable = false)
	public boolean isBsuspendido() {
		return this.bsuspendido;
	}

	public void setBsuspendido(boolean bsuspendido) {
		this.bsuspendido = bsuspendido;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planByIdplanbase")
	public Set<Plan> getPlansForIdplanbase() {
		return this.plansForIdplanbase;
	}

	public void setPlansForIdplanbase(Set<Plan> plansForIdplanbase) {
		this.plansForIdplanbase = plansForIdplanbase;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planByIdplanoperador")
	public Set<Operacionplan> getOperacionplansForIdplanoperador() {
		return this.operacionplansForIdplanoperador;
	}

	public void setOperacionplansForIdplanoperador(
			Set<Operacionplan> operacionplansForIdplanoperador) {
		this.operacionplansForIdplanoperador = operacionplansForIdplanoperador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<Tramite> getTramites() {
		return this.tramites;
	}

	public void setTramites(Set<Tramite> tramites) {
		this.tramites = tramites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planByIdplanoperado")
	public Set<Operacionplan> getOperacionplansForIdplanoperado() {
		return this.operacionplansForIdplanoperado;
	}

	public void setOperacionplansForIdplanoperado(
			Set<Operacionplan> operacionplansForIdplanoperado) {
		this.operacionplansForIdplanoperado = operacionplansForIdplanoperado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planByIdpadre")
	public Set<Plan> getPlansForIdpadre() {
		return this.plansForIdpadre;
	}

	public void setPlansForIdpadre(Set<Plan> plansForIdpadre) {
		this.plansForIdpadre = plansForIdpadre;
	}

}
