package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Propiedadrelacion generated by hbm2java
 */
@Entity
@Table(name = "propiedadrelacion")
public class Propiedadrelacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6832940689962661008L;
	private int iden;
	private Relacion relacion;
	private int iddefpropiedad;
	private String valor;

	public Propiedadrelacion() {
	}

	public Propiedadrelacion(int iden, Relacion relacion, int iddefpropiedad,
			String valor) {
		this.iden = iden;
		this.relacion = relacion;
		this.iddefpropiedad = iddefpropiedad;
		this.valor = valor;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrelacion", nullable = false)
	public Relacion getRelacion() {
		return this.relacion;
	}

	public void setRelacion(Relacion relacion) {
		this.relacion = relacion;
	}

	@Column(name = "iddefpropiedad", nullable = false)
	public int getIddefpropiedad() {
		return this.iddefpropiedad;
	}

	public void setIddefpropiedad(int iddefpropiedad) {
		this.iddefpropiedad = iddefpropiedad;
	}

	@Column(name = "valor", nullable = false)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
