package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tramite generated by hbm2java
 */
@Entity
@Table(name = "tramite", uniqueConstraints = @UniqueConstraint(columnNames = "codigofip"))
public class Tramite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3411681525493479307L;
	private int iden;
	private Plan plan;
	private int idtipotramite;
	private Integer idorgano;
	private Integer idsentido;
	private Date fecha;
	private String texto;
	private String comentario;
	private String numeroacuerdo;
	private String nombre;
	private int idcentroproduccion;
	private String codigofip;
	private int iteracion;
	private Date fechaconsolidacion;
	private Set<Relacion> relacionsForIdtramitecreador = new HashSet<Relacion>(
			0);
	private Set<Determinacion> determinacions = new HashSet<Determinacion>(0);
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<Operacion> operacions = new HashSet<Operacion>(0);
	private Set<Entidad> entidads = new HashSet<Entidad>(0);
	private Set<Relacion> relacionsForIdtramiteborrador = new HashSet<Relacion>(
			0);

	public Tramite() {
	}

	public Tramite(int iden, Plan plan, int idtipotramite,
			int idcentroproduccion, String codigofip, int iteracion) {
		this.iden = iden;
		this.plan = plan;
		this.idtipotramite = idtipotramite;
		this.idcentroproduccion = idcentroproduccion;
		this.codigofip = codigofip;
		this.iteracion = iteracion;
	}

	public Tramite(int iden, Plan plan, int idtipotramite, Integer idorgano,
			Integer idsentido, Date fecha, String texto, String comentario,
			String numeroacuerdo, String nombre, int idcentroproduccion,
			String codigofip, int iteracion, Date fechaconsolidacion,
			Set<Relacion> relacionsForIdtramitecreador,
			Set<Determinacion> determinacions, Set<Documento> documentos,
			Set<Operacion> operacions, Set<Entidad> entidads,
			Set<Relacion> relacionsForIdtramiteborrador) {
		this.iden = iden;
		this.plan = plan;
		this.idtipotramite = idtipotramite;
		this.idorgano = idorgano;
		this.idsentido = idsentido;
		this.fecha = fecha;
		this.texto = texto;
		this.comentario = comentario;
		this.numeroacuerdo = numeroacuerdo;
		this.nombre = nombre;
		this.idcentroproduccion = idcentroproduccion;
		this.codigofip = codigofip;
		this.iteracion = iteracion;
		this.fechaconsolidacion = fechaconsolidacion;
		this.relacionsForIdtramitecreador = relacionsForIdtramitecreador;
		this.determinacions = determinacions;
		this.documentos = documentos;
		this.operacions = operacions;
		this.entidads = entidads;
		this.relacionsForIdtramiteborrador = relacionsForIdtramiteborrador;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idplan", nullable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@Column(name = "idtipotramite", nullable = false)
	public int getIdtipotramite() {
		return this.idtipotramite;
	}

	public void setIdtipotramite(int idtipotramite) {
		this.idtipotramite = idtipotramite;
	}

	@Column(name = "idorgano")
	public Integer getIdorgano() {
		return this.idorgano;
	}

	public void setIdorgano(Integer idorgano) {
		this.idorgano = idorgano;
	}

	@Column(name = "idsentido")
	public Integer getIdsentido() {
		return this.idsentido;
	}

	public void setIdsentido(Integer idsentido) {
		this.idsentido = idsentido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "comentario")
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "numeroacuerdo", length = 20)
	public String getNumeroacuerdo() {
		return this.numeroacuerdo;
	}

	public void setNumeroacuerdo(String numeroacuerdo) {
		this.numeroacuerdo = numeroacuerdo;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "idcentroproduccion", nullable = false)
	public int getIdcentroproduccion() {
		return this.idcentroproduccion;
	}

	public void setIdcentroproduccion(int idcentroproduccion) {
		this.idcentroproduccion = idcentroproduccion;
	}

	@Column(name = "codigofip", unique = true, nullable = false, length = 32)
	public String getCodigofip() {
		return this.codigofip;
	}

	public void setCodigofip(String codigofip) {
		this.codigofip = codigofip;
	}

	@Column(name = "iteracion", nullable = false)
	public int getIteracion() {
		return this.iteracion;
	}

	public void setIteracion(int iteracion) {
		this.iteracion = iteracion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaconsolidacion", length = 13)
	public Date getFechaconsolidacion() {
		return this.fechaconsolidacion;
	}

	public void setFechaconsolidacion(Date fechaconsolidacion) {
		this.fechaconsolidacion = fechaconsolidacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramiteByIdtramitecreador")
	public Set<Relacion> getRelacionsForIdtramitecreador() {
		return this.relacionsForIdtramitecreador;
	}

	public void setRelacionsForIdtramitecreador(
			Set<Relacion> relacionsForIdtramitecreador) {
		this.relacionsForIdtramitecreador = relacionsForIdtramitecreador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramite")
	public Set<Determinacion> getDeterminacions() {
		return this.determinacions;
	}

	public void setDeterminacions(Set<Determinacion> determinacions) {
		this.determinacions = determinacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramite")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramite")
	public Set<Operacion> getOperacions() {
		return this.operacions;
	}

	public void setOperacions(Set<Operacion> operacions) {
		this.operacions = operacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramite")
	public Set<Entidad> getEntidads() {
		return this.entidads;
	}

	public void setEntidads(Set<Entidad> entidads) {
		this.entidads = entidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramiteByIdtramiteborrador")
	public Set<Relacion> getRelacionsForIdtramiteborrador() {
		return this.relacionsForIdtramiteborrador;
	}

	public void setRelacionsForIdtramiteborrador(
			Set<Relacion> relacionsForIdtramiteborrador) {
		this.relacionsForIdtramiteborrador = relacionsForIdtramiteborrador;
	}

}
