package es.mitc.redes.urbanismoenred.data.rpm.refundido;

// Generated 03-abr-2012 12:30:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proceso generated by hbm2java
 */
@Entity(name = "es.mitc.redes.urbanismoenred.data.rpm.refundido.proceso")
@Table(name = "proceso", schema = "refundido")
public class Proceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8606557733054315172L;
	private int iden;
	private int usuario;
	private int ambito;
	private Date inicio;
	private Date fin;
	private Boolean correcto;
	private Set<Archivo> archivos = new HashSet<Archivo>(0);

	public Proceso() {
	}

	public Proceso(int iden, int usuario, int ambito, Date inicio) {
		this.iden = iden;
		this.usuario = usuario;
		this.ambito = ambito;
		this.inicio = inicio;
	}

	public Proceso(int iden, int usuario, int ambito, Date inicio, Date fin,
			Boolean correcto, Set<Archivo> archivos) {
		this.iden = iden;
		this.usuario = usuario;
		this.ambito = ambito;
		this.inicio = inicio;
		this.fin = fin;
		this.correcto = correcto;
		this.archivos = archivos;
	}

	@Id
	@Column(name = "iden", unique = true, nullable = false)
	public int getIden() {
		return this.iden;
	}

	public void setIden(int iden) {
		this.iden = iden;
	}

	@Column(name = "usuario", nullable = false)
	public int getUsuario() {
		return this.usuario;
	}

	public void setUsuario(int usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ambito", nullable = false)
	public int getAmbito() {
		return this.ambito;
	}

	public void setAmbito(int ambito) {
		this.ambito = ambito;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inicio", nullable = false, length = 35)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fin", length = 35)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "correcto")
	public Boolean getCorrecto() {
		return this.correcto;
	}

	public void setCorrecto(Boolean correcto) {
		this.correcto = correcto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<Archivo> getArchivos() {
		return this.archivos;
	}

	public void setArchivos(Set<Archivo> archivos) {
		this.archivos = archivos;
	}

}
